package hai.hms.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BSXmlWsEntryClassService service = new BSXmlWsEntryClassService();
 * BSXmlWsEntryClass portType = service.getBSXmlWsEntryClassPort();
 * portType.invoke(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BSXmlWsEntryClassService", targetNamespace = "http://ws.access.hai/", wsdlLocation = "http://192.168.10.152:9566/hai/WebServiceEntry?wsdl")
public class BSXmlWsEntryClassService extends Service {

	private final static URL BSXMLWSENTRYCLASSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(hai.hms.ws.BSXmlWsEntryClassService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = hai.hms.ws.BSXmlWsEntryClassService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.10.152:9566/hai/WebServiceEntry?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.10.152:9566/hai/WebServiceEntry?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BSXMLWSENTRYCLASSSERVICE_WSDL_LOCATION = url;
	}

	public BSXmlWsEntryClassService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BSXmlWsEntryClassService() {
		super(BSXMLWSENTRYCLASSSERVICE_WSDL_LOCATION, new QName(
				"http://ws.access.hai/", "BSXmlWsEntryClassService"));
	}

	/**
	 * 
	 * @return returns BSXmlWsEntryClass
	 */
	@WebEndpoint(name = "BSXmlWsEntryClassPort")
	public BSXmlWsEntryClass getBSXmlWsEntryClassPort() {
		return super.getPort(new QName("http://ws.access.hai/",
				"BSXmlWsEntryClassPort"), BSXmlWsEntryClass.class);
	}

}
