package hai.hms.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BSXmlWsEntryClass", targetNamespace = "http://ws.access.hai/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BSXmlWsEntryClass {

	/**
	 * 
	 * @param pwd
	 * @param urid
	 * @param parameter
	 * @param service
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String invoke(
			@WebParam(name = "service", partName = "service") String service,
			@WebParam(name = "urid", partName = "urid") String urid,
			@WebParam(name = "pwd", partName = "pwd") String pwd,
			@WebParam(name = "parameter", partName = "parameter") String parameter);

}
