$package("chis.application.mhc.script.deliveryHtml")
chis.application.mhc.script.deliveryHtml.DebilityChildrenRecordHtmlFormTemplate = {

	getDebilityChildrenRecordHtmlFormTemplate : function() {
		var tpl = 
				 '<div class="my"> '
				+ '<table width="850" border="0" align="center" cellpadding="0" cellspacing="0" class="table1">'
				+ '<tbody>'
				+ '<tr>'
				+ '<td align="center" width="75"><strong class="fieldColor">姓名</strong></td>'
				+ '<td colspan="2" width="150"><input type="text"  id="babyName'+ this.idPostfix+'" name="babyName" class="width140 input_btline" /></td>'
				+ '<td align="center" id="babySexField'+this.idPostfix+'"><strong class="fieldColor">性 别</strong></td>'
				+ '<td colspan="5" width="375"><div id="div_babySex'+this.idPostfix+'">' 
				+ '<input type="radio" id="babySex_0'+ this.idPostfix+'" name="babySex" value="0"/>未知的性别 ' 
				+ '<input type="radio" id="babySex_1'+ this.idPostfix+'" name="babySex" value="1"/>男 ' 
				+ '<input type="radio" id="babySex_2'+ this.idPostfix+'" name="babySex" value="2"/>女　　' 
				+ '<input type="radio" id="babySex_9'+ this.idPostfix+'" name="babySex" value="9"/>未说明的性别'
				+ '</div></td>'
				+ '<td align="center" width="75" id="babyBirthField'+this.idPostfix+'" ><strong class="fieldColor">出生日期</strong></td>'
				+ '<td colspan="2" width="150"><div  id="babyBirth'+ this.idPostfix+ '"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  align="center" style="font-weight:bold;"><strong class="fieldColor">身份证号</strong></td>'
				+ '<td colspan="2"><input  id="babyIdCard'+ this.idPostfix+ '" name="babyIdCard" class="width140 input_btline" />' 
				+'</td>'
				+ '<td align="center" ><strong class="fieldColor">出生证号</strong></td>'
				+ '<td colspan="2"><input type="text" id="certificateNo'+ this.idPostfix+ '" class="width120 input_btline" /></td>'
				+ '<td  align="center"><strong class="fieldColor">家庭住址</strong></td>'
				+ '<td colspan="5"><input type="text" id="babyAddress'
				+ this.idPostfix
				+ '" class="width300 input_btline" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  align="center" width="75"><strong class="fieldColor">父亲姓名</strong></td>'
				+ '<td colspan="2" width="150"><div id="fatherName'
				+ this.idPostfix
				+ '"/></td>'
				+ '<td align="center" width="75"><strong class="fieldColor">职业</strong></td>'
				+ '<td colspan="2" width="150"><div id="fatherJob'
				+ this.idPostfix
				+ '" class="width80 input_btline" /></td>'
				+ '<td align="center" width="75"><strong class="fieldColor">联系电话</strong></td>'
				+ '<td colspan="2" width="150"><input type="text" id="fatherPhone'
				+ this.idPostfix
				+ '" class="width100 input_btline" /></td>'
				+ '<td align="center" width="75"><strong class="fieldColor">出生日期</strong></td>'
				+ '<td colspan="2" width="150"><div id="fatherBirth'
				+ this.idPostfix
				+ '" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  align="center"><strong class="fieldColor">母亲姓名</strong></td>'
				+ '<td colspan="2"><input type="text" id="motherName'
				+ this.idPostfix
				+ '" class="width140 input_btline" /></td>'
				+ '<td  align="center"><strong class="fieldColor">职业</strong></td>'
				+ '<td colspan="2"><div id="motherJob'
				+ this.idPostfix
				+ '" class="width80 input_btline" /></td>'
				+ '<td  align="center"><strong class="fieldColor">联系电话</strong></td>'
				+ '<td colspan="2"><input type="text" id="motherPhone'
				+ this.idPostfix
				+ '" class="width100 input_btline" /></td>'
				+ '<td  align="center"><strong class="fieldColor">出生日期</strong></td>'
				+ '<td colspan="2"><div  id="motherBirth'
				+ this.idPostfix
				+ '" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  align="center"><strong class="fieldColor">出生孕周</strong></td>'
				+ '<td colspan="2"><input type="text" id="gestation'
				+ this.idPostfix
				+ '" class="width120 input_btline" />周</td>'
				+ '<td align="center" colspan="2"><strong class="fieldColor">母亲妊娠期患病情况</strong></td>'
				+ '<td colspan="7">'
				+ '<input type="radio"  id="pregnancyDisease_1'+this.idPostfix+ '" name="pregnancyDisease" value="1"/>糖尿病 '
				+ '<input type="radio"  id="pregnancyDisease_2'+this.idPostfix+'" name="pregnancyDisease" value="2"/>妊娠期高血压 ' 
				+ '<input type="radio"  id="pregnancyDisease_3'+this.idPostfix+'" name="pregnancyDisease" value="3"/>其他'
				+ '<input type="text" id="otherDisease'+ this.idPostfix+ '" class="width230 input_btline" />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center"><strong class="fieldColor">助产机构名称</strong></td>'
				+ '<td colspan="2"><input type="text" id="deliveryUnit'
				+ this.idPostfix
				+ '" class="width140 input_btline" /></td>'
				+ '<td align="center"><strong class="fieldColor">出生情况</strong></td>'
				+ '<td colspan="7">'
				+ '<input type="checkbox" id="birthStatus_1'+this.idPostfix+'" name="birthStatus" value="1"/>顺产'
				+ '<input type="checkbox" id="birthStatus_2'+this.idPostfix+'" name="birthStatus" value="2"/>胎头吸引 ' 
				+ '<input type="checkbox" id="birthStatus_3'+this.idPostfix+'" name="birthStatus" value="3"/>产钳'
				+ '<input type="checkbox" id="birthStatus_4'+this.idPostfix+'" name="birthStatus" value="4"/>剖宫 '
				+ '<input type="checkbox" id="birthStatus_5'+this.idPostfix+'" name="birthStatus" value="5"/>双多胎 ' 
				+ '<input type="checkbox" id="birthStatus_6'+this.idPostfix+'" name="birthStatus" value="6"/>臀位 <br />' 
				+ '<input type="checkbox" id="birthStatus_7'+this.idPostfix+'" name="birthStatus" value="7"/>其他' 
				+ '<input type="text" id="otherStatus' + this.idPostfix + '" class="width360 input_btline" />' 
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  align="center"><strong class="fieldColor">新生儿窒息</strong></td>'
				+ '<td colspan="4">'
				+ '<input type="radio" id="asphyxia_n'+this.idPostfix+'" name="asphyxia" value="n"/>无'
				+ '<input type="radio" id="asphyxia_y'+this.idPostfix+'" name="asphyxia" value="y"/>有'
				+ '</td>'
				+ '<td  rowspan="2" colspan="2" align="center"><strong class="fieldColor">是否有畸型</strong></td>'
				+ '<td rowspan="2" colspan="5">'
				+ '<input type="radio" id="malforMation_n'+this.idPostfix+'" name="malforMation" value="n"/>无 '
				+ '<input type="radio" id="malforMation_y'+this.idPostfix+'" name="malforMation" value="y"/>有'
				+ '<input type="text" id="malforMationDescription'+ this.idPostfix+ '" class="width180 input_btline"/>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  align="center"><strong class="fieldColor">Apgar评分</strong></td>'
				+ '<td colspan="4">1分钟<input type="text" id="apgar1'
				+ this.idPostfix
				+ '" class="width80 input_btline"/>5分钟<input type="text" id="apgar5'
				+ this.idPostfix
				+ '" class="width120 input_btline"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  align="center"><strong class="fieldColor">听力筛查</strong></td>'
				+ '<td colspan="11">'
				+ '<input type="radio" id="hearingTest_1'+this.idPostfix+'" name="hearingTest" value="1"/>通过 '
				+ '<input type="radio" id="hearingTest_2'+this.idPostfix+'" name="hearingTest" value="2"/>未通过 '
				+ '<input type="radio" id="hearingTest_3'+this.idPostfix+'" name="hearingTest" value="3"/>未筛查 ' 
				+ '<input type="radio" id="hearingTest_4'+this.idPostfix+'" name="hearingTest" value="4"/>不详'
				+ ' </td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  align="center"><strong class="fieldColor">疾病筛查</strong></td>'
				+ '<td colspan="11">' 
				+ '<input type="radio" id="illnessScreening_1'+ this.idPostfix+'" name="illnessScreening" value="1"/>甲低 ' 
				+ '<input type="radio" id="illnessScreening_2'+ this.idPostfix+'" name="illnessScreening" value="2"/>苯丙酮尿症'
				+ '<input type="radio" id="illnessScreening_3'+ this.idPostfix+'" name="illnessScreening" value="3"/>其他遗传代谢病'
				+ '<input type="text" id="otherIllness'+ this.idPostfix+ '" class="width360 input_btline" />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td   align="center" class="tdnone"><strong class="fieldColor">出生体重</strong></td>'
				+ '<td colspan="5"><input type="text" id="weight'
				+ this.idPostfix + '" class="width140 input_btline" />kg</td>'
				+ '<td align="center"  class="tdnone"><strong class="fieldColor">出生身长</strong></td>'
				+ '<td colspan="5"><input type="text" id="length' + this.idPostfix
				+ '" class=" input_btline" />cm</td>' + '</tr>'
				+ '</tbody>' + '</table>' + '</div>';
		return tpl;
	}
}