
package Hcnservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HCNWebservices", targetNamespace = "http://webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HCNWebservices {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://webservices/", className = "Hcnservices.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://webservices/", className = "Hcnservices.GetValueResponse")
    @Action(input = "http://webservices/HCNWebservices/getValueRequest", output = "http://webservices/HCNWebservices/getValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "docheckGRZH", targetNamespace = "http://webservices/", className = "Hcnservices.DocheckGRZH")
    @ResponseWrapper(localName = "docheckGRZHResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DocheckGRZHResponse")
    @Action(input = "http://webservices/HCNWebservices/docheckGRZHRequest", output = "http://webservices/HCNWebservices/docheckGRZHResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/docheckGRZH/Fault/Exception")
    })
    public String docheckGRZH(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dogetYpml", targetNamespace = "http://webservices/", className = "Hcnservices.DogetYpml")
    @ResponseWrapper(localName = "dogetYpmlResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DogetYpmlResponse")
    @Action(input = "http://webservices/HCNWebservices/dogetYpmlRequest", output = "http://webservices/HCNWebservices/dogetYpmlResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/dogetYpml/Fault/Exception")
    })
    public String dogetYpml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dogetZlml", targetNamespace = "http://webservices/", className = "Hcnservices.DogetZlml")
    @ResponseWrapper(localName = "dogetZlmlResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DogetZlmlResponse")
    @Action(input = "http://webservices/HCNWebservices/dogetZlmlRequest", output = "http://webservices/HCNWebservices/dogetZlmlResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/dogetZlml/Fault/Exception")
    })
    public String dogetZlml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dogetJbml", targetNamespace = "http://webservices/", className = "Hcnservices.DogetJbml")
    @ResponseWrapper(localName = "dogetJbmlResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DogetJbmlResponse")
    @Action(input = "http://webservices/HCNWebservices/dogetJbmlRequest", output = "http://webservices/HCNWebservices/dogetJbmlResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/dogetJbml/Fault/Exception")
    })
    public String dogetJbml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dogetDbzml", targetNamespace = "http://webservices/", className = "Hcnservices.DogetDbzml")
    @ResponseWrapper(localName = "dogetDbzmlResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DogetDbzmlResponse")
    @Action(input = "http://webservices/HCNWebservices/dogetDbzmlRequest", output = "http://webservices/HCNWebservices/dogetDbzmlResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/dogetDbzml/Fault/Exception")
    })
    public String dogetDbzml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "douploadDzml", targetNamespace = "http://webservices/", className = "Hcnservices.DouploadDzml")
    @ResponseWrapper(localName = "douploadDzmlResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DouploadDzmlResponse")
    @Action(input = "http://webservices/HCNWebservices/douploadDzmlRequest", output = "http://webservices/HCNWebservices/douploadDzmlResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/douploadDzml/Fault/Exception")
    })
    public String douploadDzml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doMzdj", targetNamespace = "http://webservices/", className = "Hcnservices.DoMzdj")
    @ResponseWrapper(localName = "doMzdjResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoMzdjResponse")
    @Action(input = "http://webservices/HCNWebservices/doMzdjRequest", output = "http://webservices/HCNWebservices/doMzdjResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doMzdj/Fault/Exception")
    })
    public String doMzdj(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doFybxYjsDrgs", targetNamespace = "http://webservices/", className = "Hcnservices.DoFybxYjsDrgs")
    @ResponseWrapper(localName = "doFybxYjsDrgsResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoFybxYjsDrgsResponse")
    @Action(input = "http://webservices/HCNWebservices/doFybxYjsDrgsRequest", output = "http://webservices/HCNWebservices/doFybxYjsDrgsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doFybxYjsDrgs/Fault/Exception")
    })
    public String doFybxYjsDrgs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doFybxJsDrgs", targetNamespace = "http://webservices/", className = "Hcnservices.DoFybxJsDrgs")
    @ResponseWrapper(localName = "doFybxJsDrgsResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoFybxJsDrgsResponse")
    @Action(input = "http://webservices/HCNWebservices/doFybxJsDrgsRequest", output = "http://webservices/HCNWebservices/doFybxJsDrgsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doFybxJsDrgs/Fault/Exception")
    })
    public String doFybxJsDrgs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doUploadFyxx", targetNamespace = "http://webservices/", className = "Hcnservices.DoUploadFyxx")
    @ResponseWrapper(localName = "doUploadFyxxResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoUploadFyxxResponse")
    @Action(input = "http://webservices/HCNWebservices/doUploadFyxxRequest", output = "http://webservices/HCNWebservices/doUploadFyxxResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doUploadFyxx/Fault/Exception")
    })
    public String doUploadFyxx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doFybxYjs", targetNamespace = "http://webservices/", className = "Hcnservices.DoFybxYjs")
    @ResponseWrapper(localName = "doFybxYjsResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoFybxYjsResponse")
    @Action(input = "http://webservices/HCNWebservices/doFybxYjsRequest", output = "http://webservices/HCNWebservices/doFybxYjsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doFybxYjs/Fault/Exception")
    })
    public String doFybxYjs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doFYbxjs", targetNamespace = "http://webservices/", className = "Hcnservices.DoFYbxjs")
    @ResponseWrapper(localName = "doFYbxjsResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoFYbxjsResponse")
    @Action(input = "http://webservices/HCNWebservices/doFYbxjsRequest", output = "http://webservices/HCNWebservices/doFYbxjsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doFYbxjs/Fault/Exception")
    })
    public String doFYbxjs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doReSaveFybx", targetNamespace = "http://webservices/", className = "Hcnservices.DoReSaveFybx")
    @ResponseWrapper(localName = "doReSaveFybxResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoReSaveFybxResponse")
    @Action(input = "http://webservices/HCNWebservices/doReSaveFybxRequest", output = "http://webservices/HCNWebservices/doReSaveFybxResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doReSaveFybx/Fault/Exception")
    })
    public String doReSaveFybx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doZydj", targetNamespace = "http://webservices/", className = "Hcnservices.DoZydj")
    @ResponseWrapper(localName = "doZydjResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoZydjResponse")
    @Action(input = "http://webservices/HCNWebservices/doZydjRequest", output = "http://webservices/HCNWebservices/doZydjResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doZydj/Fault/Exception")
    })
    public String doZydj(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doCancleZydj", targetNamespace = "http://webservices/", className = "Hcnservices.DoCancleZydj")
    @ResponseWrapper(localName = "doCancleZydjResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoCancleZydjResponse")
    @Action(input = "http://webservices/HCNWebservices/doCancleZydjRequest", output = "http://webservices/HCNWebservices/doCancleZydjResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doCancleZydj/Fault/Exception")
    })
    public String doCancleZydj(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doMrdzMx", targetNamespace = "http://webservices/", className = "Hcnservices.DoMrdzMx")
    @ResponseWrapper(localName = "doMrdzMxResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoMrdzMxResponse")
    @Action(input = "http://webservices/HCNWebservices/doMrdzMxRequest", output = "http://webservices/HCNWebservices/doMrdzMxResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doMrdzMx/Fault/Exception")
    })
    public String doMrdzMx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "startwebservice", targetNamespace = "http://webservices/", className = "Hcnservices.Startwebservice")
    @ResponseWrapper(localName = "startwebserviceResponse", targetNamespace = "http://webservices/", className = "Hcnservices.StartwebserviceResponse")
    @Action(input = "http://webservices/HCNWebservices/startwebserviceRequest", output = "http://webservices/HCNWebservices/startwebserviceResponse")
    public void startwebservice();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dogetDzmlByItem", targetNamespace = "http://webservices/", className = "Hcnservices.DogetDzmlByItem")
    @ResponseWrapper(localName = "dogetDzmlByItemResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DogetDzmlByItemResponse")
    @Action(input = "http://webservices/HCNWebservices/dogetDzmlByItemRequest", output = "http://webservices/HCNWebservices/dogetDzmlByItemResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/dogetDzmlByItem/Fault/Exception")
    })
    public String dogetDzmlByItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doReSaveFybxDrgs", targetNamespace = "http://webservices/", className = "Hcnservices.DoReSaveFybxDrgs")
    @ResponseWrapper(localName = "doReSaveFybxDrgsResponse", targetNamespace = "http://webservices/", className = "Hcnservices.DoReSaveFybxDrgsResponse")
    @Action(input = "http://webservices/HCNWebservices/doReSaveFybxDrgsRequest", output = "http://webservices/HCNWebservices/doReSaveFybxDrgsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/HCNWebservices/doReSaveFybxDrgs/Fault/Exception")
    })
    public String doReSaveFybxDrgs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
