$package("chis.application.tb.script");

chis.application.tb.script.TuberculosisFirstVisitHtmlTemplate = {
	getTBVisitHTMLTemplate : function() {
		var html = '<div class="my">'
				+ '<input id="visitId'+this.idPostfix+'" name="visitId" type="hidden" title="随访ID"/>'
				+ '<input id="phrId'+this.idPostfix+'" name="phrId" type="hidden" title="档案编号"/>'
				+ '<input id="empiId'+this.idPostfix+'" name="empiId" type="hidden" title="EMPIID"/>'
				+ '<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">'
				+ '<tr>'
				
				+ '<td align="center" colspan="3">'
				+ '<div align="center"><strong>随访时间</strong></div>'
				+ '</td>'
				+ '<td><div id="div_visitDate' + this.idPostfix + '"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="3"><div align="center"><strong>随访方式</strong></div></td>'
				+ '<td width="423"><label for="visitType_1' + this.idPostfix + '">'
				+ '<input name="visitType" type="radio" id="visitType_1' + this.idPostfix + '" value="1" />'
				+ '门诊</label> '
				+ '<label for="visitType_2' + this.idPostfix + '">'
				+ '<input name="visitType" type="radio" id="visitType_2' + this.idPostfix + '" value="2" />'
				+ '家庭</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="3"><div align="center"><strong>患者类型</strong></div></td>'
				+ '<td width="423"><label for="patientType_1' + this.idPostfix + '">'
				+ '<input name="patientType" type="radio" id="patientType_1' + this.idPostfix + '" value="1" />'
				+ '初治</label> '
				+ '<label for="patientType_2' + this.idPostfix + '">'
				+ '<input name="patientType" type="radio" id="patientType_2' + this.idPostfix + '" value="2" />'
				+ '复治</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="3"><div align="center"><strong>痰菌情况</strong></div></td>'
				+ '<td width="423"><label for="sputumStatus_1' + this.idPostfix + '">'
				+ '<input name="sputumStatus" type="radio" id="sputumStatus_1' + this.idPostfix + '" value="1" />'
				+ '阳性</label> '
				+ '<label for="sputumStatus_2' + this.idPostfix + '">'
				+ '<input name="sputumStatus" type="radio" id="sputumStatus_2' + this.idPostfix + '" value="2" />'
				+ '阴性</label> '
				+ '<label for="sputumStatus_3' + this.idPostfix + '">'
				+ '<input name="sputumStatus" type="radio" id="sputumStatus_3' + this.idPostfix + '" value="3" />'
				+ '未查痰</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="3"><div align="center"><strong>耐药情况</strong></div></td>'
				+ '<td width="423"><label for="resistanceStatus_1' + this.idPostfix + '">'
				+ '<input name="resistanceStatus" type="radio" id="resistanceStatus_1' + this.idPostfix + '" value="1" />'
				+ '耐药</label> '
				+ '<label for="resistanceStatus_2' + this.idPostfix + '">'
				+ '<input name="resistanceStatus" type="radio" id="resistanceStatus_2' + this.idPostfix + '" value="2" />'
				+ '非耐药</label> '
				+ '<label for="resistanceStatus_3' + this.idPostfix + '">'
				+ '<input name="resistanceStatus" type="radio" id="resistanceStatus_3' + this.idPostfix + '" value="3" />'
				+ '未检测</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="medium" align="center" colspan="3" rowspan="2"><div align="center"><strong>症状及体征</strong></div></td>'
				+ '<td valign="top"><label for="symptomSign_0' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_0' + this.idPostfix + '" value="0" />'
				+ '没有症状</label> '
				+ '<label for="symptomSign_1' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_1' + this.idPostfix + '" value="1" />'
				+ '咳嗽咳痰</label> '
				+ '<label for="symptomSign_2' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_2' + this.idPostfix + '" value="2" />'
				+ '低热盗汗</label> '
				+ '<label for="symptomSign_3' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_3' + this.idPostfix + '" value="3" />'
				+ '咯血或血痰</label> '
				+ '<label for="symptomSign_4' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_4' + this.idPostfix + '" value="4" />'
				+ '胸痛消瘦</label> '
				+ '<label for="symptomSign_5' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_5' + this.idPostfix + '" value="5" />'
				+ '恶心纳差</label> '
				+ '<label for="symptomSign_6' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_6' + this.idPostfix + '" value="6" />'
				+ '头痛失眠</label> '
				+ '<label for="symptomSign_7' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_7' + this.idPostfix + '" value="7" />'
				+ '视物模糊</label> '
				+ '<label for="symptomSign_8' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_8' + this.idPostfix + '" value="8" />'
				+ '皮肤瘙痒、皮疹</label> '
				+ '<label for="symptomSign_9' + this.idPostfix + '">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_9' + this.idPostfix + '" value="9" />'
				+ '耳鸣、听力下降</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top">其他：'
				+ '<input name="otherSymptomSign" type="text" id="otherSymptomSign' + this.idPostfix + '" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="medium" colspan="2" rowspan="3"><div align="center"><strong>用 药</strong></div></td>'
				+ '<td width="193" align="center"><div align="center"><strong>化疗方案</strong></div></td>'
				+ '<td valign="top"><input name="chemotherapy" type="text" id="chemotherapy' + this.idPostfix + '" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="193" align="center"><div align="center"><strong>用法</strong></div></td>'
				+ '<td valign="top"><label for="medicineUsage_1' + this.idPostfix + '">'
				+ '<input type="radio" name="medicineUsage" id="medicineUsage_1' + this.idPostfix + '" value="1" />'
				+ '每日</label> '
				+ '<label for="medicineUsage_2' + this.idPostfix + '">'
				+ '<input type="radio" name="medicineUsage" id="medicineUsage_2' + this.idPostfix + '" value="2" />'
				+ '间歇</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="193" align="center"><div align="center"><strong>药品剂型</strong></div></td>'
				+ '<td valign="top"><label for="medicineType_1' + this.idPostfix + '">'
				+ '<input name="medicineType" type="radio" id="medicineType_1' + this.idPostfix + '" value="1" />'
				+ '固定剂量复制剂</label> '
				+ '<label for="medicineType_2' + this.idPostfix + '">'
				+ '<input name="medicineType" type="radio" id="medicineType_2' + this.idPostfix + '" value="2" />'
				+ '散装药</label> '
				+ '<label for="medicineType_3' + this.idPostfix + '">'
				+ '<input name="medicineType" type="radio" id="medicineType_3' + this.idPostfix + '" size="3" />'
				+ '板式组合药</label> '
				+ '<label for="medicineType_4' + this.idPostfix + '">'
				+ '<input name="medicineType" type="radio" id="medicineType_4' + this.idPostfix + '" value="4" />'
				+ '注射剂</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" align="center" colspan="3"><strong>督导人员选择</strong></td>'
				+ '<td valign="top">'
				+ '<label for="supervisor_1' + this.idPostfix + '">'
				+ '<input type="radio" name="supervisor" id="supervisor_1' + this.idPostfix + '" value="1" />'
				+ '医生'
				+ '</label>'
				+ '<label for="supervisor_2' + this.idPostfix + '">'
				+ '<input type="radio" name="supervisor" id="supervisor_2' + this.idPostfix + '" value="2" />'
				+ '家属'
				+ '</label>'
				+ '<label for="supervisor_3' + this.idPostfix + '">'
				+ '<input type="radio" name="supervisor" id="supervisor_3' + this.idPostfix + '" value="3" />'
				+ '自服药'
				+ '</label>'
				+ '<label for="supervisor_4' + this.idPostfix + '">'
				+ '<input type="radio" name="supervisor" id="supervisor_4' + this.idPostfix + '" value="4" />'
				+ '其他 '
				+ '</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2" rowspan="2"><strong>家庭居住环境评估</strong></td>'
				+ '<td width="193" valign="top"><div align="center"><strong>单独的居室</strong></div></td>'
				+ '<td valign="top">'
				+ '<label for="singleRoom_1' + this.idPostfix + '">'
				+ '<input type="radio" name="singleRoom" id="singleRoom_1' + this.idPostfix + '" value="1" />'
				+ '有'
				+ '</label>'
				+ '<label for="singleRoom_2' + this.idPostfix + '">'
				+ '<input type="radio" name="singleRoom" id="singleRoom_2' + this.idPostfix + '" value="2" />'
				+ '无'
				+ '</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="193" valign="top"><div align="center"><strong>通风情况</strong></div></td>'
				+ '<td valign="top">'
				+ '<label for="vertilation_1' + this.idPostfix + '">'
				+ '<input type="radio" name="vertilation" id="vertilation_1' + this.idPostfix + '" value="1" />'
				+ '良好'
				+ '</label>'
				+ '<label for="vertilation_2' + this.idPostfix + '">'
				+ '<input type="radio" name="vertilation" id="vertilation_2' + this.idPostfix + '" value="2" />'
				+ '一般</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2" rowspan="2"><strong>生活方式评估</strong></td>'
				+ '<td width="193" valign="top"><div align="center"><strong>吸烟</strong></div></td>'
				+ '<td valign="top"><input name="smokePerDay" type="text" id="smokePerDay' + this.idPostfix + '" size="3" />'
				+ '/'
				+ '<input name="smokeDay" type="text" id="smokeDay' + this.idPostfix + '" size="3" />'
				+ '支/天</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="193" valign="top"><div align="center"><strong>饮酒</strong></div></td>'
				+ '<td valign="top"><input name="drinkPerDay" type="text" id="drinkPerDay' + this.idPostfix + '" size="3" />'
				+ '/'
				+ '<input name="drinkDay" type="text" id="drinkDay' + this.idPostfix + '" size="3" />'
				+ '两/天</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="193" rowspan="10" align="center" valign="center"><strong>健康教育及培训</strong></td>'
				+ '<td align="center" colspan="2"><strong>取药地点、时间</strong></td>'
				+ '<td valign="top">地点:'
				+ '<input name="takeLocation" type="text" id="takeLocation' + this.idPostfix + '" />'
				+ '<br/><span style="float:left">时间:</span><div id="div_takeTime' + this.idPostfix + '"></div>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>服药记录卡的填写</strong></td>'
				+ '<td valign="top">'
				+ '<label for="medicineRecordFill_1' + this.idPostfix + '">'
				+ '<input name="medicineRecordFill" type="radio" id="medicineRecordFill_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="medicineRecordFill_2' + this.idPostfix + '">'
				+ '<input name="medicineRecordFill" type="radio" id="medicineRecordFill_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>服药方法及药品存放</strong></td>'
				+ '<td valign="top">'
				+ '<label for="medicineStore_1' + this.idPostfix + '">'
				+ '<input name="medicineStore" type="radio" id="medicineStore_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="medicineStore_2' + this.idPostfix + '">'
				+ '<input name="medicineStore" type="radio" id="medicineStore_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>肺结核治疗疗程</strong></td>'
				+ '<td valign="top">'
				+ '<label for="treatmentCourse_1' + this.idPostfix + '">'
				+ '<input name="treatmentCourse" type="radio" id="treatmentCourse_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="treatmentCourse_2' + this.idPostfix + '">'
				+ '<input name="treatmentCourse" type="radio" id="treatmentCourse_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>不规律服药危害</strong></td>'
				+ '<td valign="top">'
				+ '<label for="noRegularMedicineRisk_1' + this.idPostfix + '">'
				+ '<input name="noRegularMedicineRisk" type="radio" id="noRegularMedicineRisk_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="noRegularMedicineRisk_2' + this.idPostfix + '">'
				+ '<input name="noRegularMedicineRisk" type="radio" id="noRegularMedicineRisk_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>服药后不良反应及处理</strong></td>'
				+ '<td valign="top">'
				+ '<label for="medicineBadReactionTreatment_1' + this.idPostfix + '">'
				+ '<input name="medicineBadReactionTreatment" type="radio" id="medicineBadReactionTreatment_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="medicineBadReactionTreatment_2' + this.idPostfix + '">'
				+ '<input name="medicineBadReactionTreatment" type="radio" id="medicineBadReactionTreatment_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>治疗期间复诊查痰</strong></td>'
				+ '<td valign="top">'
				+ '<label for="treatmentReferralSputum_1' + this.idPostfix + '">'
				+ '<input name="treatmentReferralSputum" type="radio" id="treatmentReferralSputum_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="treatmentReferralSputum_2' + this.idPostfix + '">'
				+ '<input name="treatmentReferralSputum" type="radio" id="treatmentReferralSputum_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>外出期间如何坚持服药</strong></td>'
				+ '<td valign="top">'
				+ '<label for="persistMedicineDuringOut_1' + this.idPostfix + '">'
				+ '<input name="persistMedicineDuringOut" type="radio" id="persistMedicineDuringOut_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="persistMedicineDuringOut_2' + this.idPostfix + '">'
				+ '<input name="persistMedicineDuringOut" type="radio" id="persistMedicineDuringOut_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>生活习惯及注意事项</strong></td>'
				+ '<td valign="top">'
				+ '<label for="lifestylePrecautions_1' + this.idPostfix + '">'
				+ '<input name="lifestylePrecautions" type="radio" id="lifestylePrecautions_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="lifestylePrecautions_2' + this.idPostfix + '">'
				+ '<input name="lifestylePrecautions" type="radio" id="lifestylePrecautions_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center" colspan="2"><strong>密切接触者检查</strong></td>'
				+ '<td valign="top">'
				+ '<label for="closeContactsCheck_1' + this.idPostfix + '">'
				+ '<input name="closeContactsCheck" type="radio" id="closeContactsCheck_1' + this.idPostfix + '" value="1" />'
				+ '掌握 '
				+ '</label>'
				+ '<label for="closeContactsCheck_2' + this.idPostfix + '">'
				+ '<input name="closeContactsCheck" type="radio" id="closeContactsCheck_2' + this.idPostfix + '" value="2" />'
				+ '未掌握</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="3"><div align="center"><strong>下次随访时间</strong></div></td>'
				+ '<td valign="top"><div id="div_nextDate' + this.idPostfix + '"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="3"><div align="center"><strong>评估医生签名</strong></div></td>'
				+ '<td valign="top"><div id="div_visitDoctor' + this.idPostfix + '"></div></td>'
				
				+ '</tr></table></div>';
		return html;
	}
}