$package("chis.application.hc.script")

chis.application.hc.script.HealthCheckTemplate = {
	inhospitalList :[
	{id:'situationId',type:'hidden'},
	{id:'inhospitalDate',type:"div"},
	{id:'outhospitalDate',type:'div'},
	{id:'inhospitalReason',type:'text'},
	{id:'medicalestablishmentName',type:'text'},
	{id:'medicalrecordNumber',type:'text'}
	],
	medicine :[
	{id:'situationId',type:'hidden',alias:'记录序号'},
	{id:'medicine',type:'div',alias:'药物名称'},
	{id:'use',type:'text',alias:'用法'},
	{id:'eachDose',type:'text',alias:'用量'},
	{id:'useDate',type:'text',alias:'用药时间'},
	{id:'medicineYield',type:'radio',dic:["1","2","3"],alias:'服药依从性'}
	],
	nonimmuneInoculation : [
	{id:'recordId',type:'hidden'},
	{id:'name',type:'text'},
	{id:'inoculationDate',type:'div'},
	{id:'inoculationUnit',type:'text'}
	],
	getHealthCheckHTML : function() {
		var html = '<table width="800" border="0" align="left" cellpadding="0" cellspacing="0" class="info_tablesHc">'
				+ '<tr>'
				+'<input id="healthCheck'+this.idPostfix+'" name="healthCheck" type="hidden" title="检查单号"/>'
				+'<input id="empiId'+this.idPostfix+'" name="empiId" type="hidden" />'
				+'<input id="phrId'+this.idPostfix+'" name="phrId" type="hidden" />'
				+'<input id="manaUnitId'+this.idPostfix+'" name="manaUnitId" type="hidden" title="管辖机构"/>'
				+ '<td width="75"><font color="#FF0000"><strong>体检日期</strong></font></td>'
				+ '<td width="299" ><div id="div_checkDate'+this.idPostfix+'"></div></td>'
//				+ '<td width="119"><font color="#FF0000"><strong>责任医生</strong></font></td>'
//				+ '<td width="306"><div id="div_manaDoctor'+this.idPostfix+'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="4" valign="top">'
				+ '<table width="100%" cellpadding="0" cellspacing="0" border="0" id="info_tables2">'
				+ '<tr>'
				+ '<td><strong>体检途径</strong></td>'
				+ '<td colspan="4" align="center">' 
				+ '<input style="width:30px" id="checkWay_1'+this.idPostfix+'"  type="checkbox" name="checkWay" value="1"/>新建档&nbsp;'
				+ '<input style="width:30px" id="checkWay_2'+this.idPostfix+'"  type="checkbox" name="checkWay" value="2"/>老年人&nbsp;'
				+ '<input style="width:30px" id="checkWay_3'+this.idPostfix+'"  type="checkbox" name="checkWay" value="3"/>高血压&nbsp;'
				+ '<input style="width:30px" id="checkWay_4'+this.idPostfix+'"  type="checkbox" name="checkWay" value="4"/>糖尿病&nbsp;'
				+ '<input style="width:40px" id="checkWay_6'+this.idPostfix+'"  type="checkbox" name="checkWay" value="6"/>建档立卡户&nbsp;'
				+ '<input style="width:50px" id="checkWay_5'+this.idPostfix+'"  type="checkbox" name="checkWay" value="5"/>严重精神障碍患者&nbsp;'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>内容</strong></td>'
				+ '<td colspan="4" align="center"><strong>检查项目</strong></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>症状</strong></font></td>'
				+ '<td colspan="4">'
				+ '<input id="symptom_01'+this.idPostfix+'" type="checkbox" name="symptom" value="01"/>1无症状&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_02'+this.idPostfix+'" type="checkbox" name="symptom" value="02"/>2头痛&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_03'+this.idPostfix+'" type="checkbox" name="symptom" value="03"/>3头晕&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_04'+this.idPostfix+'" type="checkbox" name="symptom" value="04"/>4心悸&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_05'+this.idPostfix+'" type="checkbox" name="symptom" value="05"/>5胸闷&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_06'+this.idPostfix+'" type="checkbox" name="symptom" value="06"/>6胸痛&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_07'+this.idPostfix+'" type="checkbox" name="symptom" value="07"/>7慢性咳嗽&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_08'+this.idPostfix+'" type="checkbox" name="symptom" value="08"/>8咳痰&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_09'+this.idPostfix+'" type="checkbox" name="symptom" value="09"/>9呼吸困难&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_10'+this.idPostfix+'" type="checkbox" name="symptom" value="10"/>10多饮&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_11'+this.idPostfix+'" type="checkbox" name="symptom" value="11"/>11多尿&nbsp;&nbsp;'
				+ '<input id="symptom_12'+this.idPostfix+'" type="checkbox" name="symptom" value="12"/>12体重下降&nbsp;'
				+ '<input id="symptom_13'+this.idPostfix+'" type="checkbox" name="symptom" value="13"/>13乏力&nbsp;&nbsp;'
				+ '<input id="symptom_14'+this.idPostfix+'" type="checkbox" name="symptom" value="14"/>14关节肿痛&nbsp;'
				+ '<input id="symptom_15'+this.idPostfix+'" type="checkbox" name="symptom" value="15"/>15视力模糊&nbsp;'
				+ '<input id="symptom_16'+this.idPostfix+'" type="checkbox" name="symptom" value="16"/>16手脚麻木&nbsp;'
				+ '<input id="symptom_17'+this.idPostfix+'" type="checkbox" name="symptom" value="17"/>17尿急&nbsp;'
				+ '<input id="symptom_18'+this.idPostfix+'" type="checkbox" name="symptom" value="18"/>18尿痛&nbsp;'
				+ '<input id="symptom_19'+this.idPostfix+'" type="checkbox" name="symptom" value="19"/>19便秘&nbsp;'
				+ '<input id="symptom_20'+this.idPostfix+'" type="checkbox" name="symptom" value="20"/>20腹泻&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_21'+this.idPostfix+'" type="checkbox" name="symptom" value="21"/>21恶心呕吐&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_22'+this.idPostfix+'" type="checkbox" name="symptom" value="22"/>22眼花&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_23'+this.idPostfix+'" type="checkbox" name="symptom" value="23"/>23耳鸣&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_24'+this.idPostfix+'" type="checkbox" name="symptom" value="24"/>24乳房胀痛&nbsp;&nbsp;&nbsp;&nbsp;'
				+ '<input id="symptom_25'+this.idPostfix+'" type="checkbox" name="symptom" value="25"/>25其他'
				+ '<input id="symptomOt'+this.idPostfix+'" type="text" name="symptomOt" class="widt300"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="74" rowspan="9"><strong>一般状况</strong></td>'
				+ '<td width="152"><font color="#FF0000"><strong>体   温</strong></font></td>'
				+ '<td width="206"><input id="temperature'+this.idPostfix+'" type="text" name="temperature" class="text"  />℃</td>'
				+ '<td width="96"><font color="#FF0000"><strong>脉   率</strong></font></td>'
				+ '<td width="270"><input id="pulse'+this.idPostfix+'" type="text" name="pulse" class="text"  />次/分钟</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="2"><font color="#FF0000"><strong>呼吸频率</strong></font></td>'
				+ '<td rowspan="2"><input id="breathe'+this.idPostfix+'" type="text" name="breathe" class="text"  />次/分钟</td>'
				+ '<td rowspan="2"><font color="#FF0000"><strong>血   压</strong></font></td>'
				+ '<td><font id="BPRight'+this.idPostfix+'" color="#FF0000"><strong>右 侧</strong></font><input id="constriction'+this.idPostfix+'" type="text" name="constriction" class="widt80"  title="收缩压R(mmHg)"/>/<input id="diastolic'+this.idPostfix+'" type="text" name="diastolic" class="widt80"  title="舒张压R(mmHg)"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font id="BPLeft'+this.idPostfix+'" color="#FF0000"><strong>左 侧</strong></font><input id="constriction_L'+this.idPostfix+'" type="text" name="constriction_L" class="widt80"  title="收缩压L(mmHg)"/>/<input id="diastolic_L'+this.idPostfix+'" type="text" name="diastolic_L" class="widt80"  title="舒张压L(mmHg)"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>身   高</strong></font></td>'
				+ '<td><input id="height'+this.idPostfix+'" type="text" name="height" class="text"/>cm</td>'
				+ '<td><font color="#FF0000"><strong>体   重</strong></font></td>'
				+ '<td><input id="weight'+this.idPostfix+'" type="text" name="weight" class="text"/>kg</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>腰   围</strong></font></td>'
				+ '<td><input id="waistline'+this.idPostfix+'" type="text" name="waistline" class="text"  />cm</td>'
				+ '<td><font color="#FF0000">体质指数（BMI）</font></td>'
				+ '<td><input id="bmi'+this.idPostfix+'" type="text" name="bmi" class="text"  />Kg/m2</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>老年人健康状态自我评估*</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="healthStatus_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="healthStatus" value="1"/>满意&nbsp;'
				+ '<input id="healthStatus_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="healthStatus" value="2"/>基本满意&nbsp;'
				+ '<input id="healthStatus_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="healthStatus" value="3"/>说不清楚&nbsp;'
				+ '<input id="healthStatus_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="healthStatus" value="4"/>不太满意&nbsp;'
				+ '<input id="healthStatus_5'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="healthStatus" value="5"/>不满意&nbsp;'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>老年人生活自理能力自我评估*</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="selfCare_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="selfCare" value="1"/>可自理（0～3分）'
				+ '<input id="selfCare_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="selfCare" value="2"/>轻度依赖（4～8分）'
				+ '<input id="selfCare_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="selfCare" value="3"/>中度依赖（9～18分)'
				+ '<input id="selfCare_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="selfCare" value="4"/>不能自理（≥19分）'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>老年人认知功能*</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="cognitive_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="cognitive" value="1"/>粗筛阴性&nbsp;'
				+ '<input id="cognitive_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="cognitive" value="2"/>粗筛阳性&nbsp;' 
				+'，简易智力状态检查，&nbsp;&nbsp;&nbsp;总分<input id="cognitiveZf'+this.idPostfix+'" type="text" name="cognitiveZf" class="text"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>老年人情感状态*</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="emotion_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="emotion" value="1" />粗筛阴性&nbsp;'
				+ '<input id="emotion_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="emotion" value="2" />粗筛阳性&nbsp;' 
				+ '，老年人抑郁评分检查，总分<input id="emotionZf'+this.idPostfix+'" type="text" name="emotionZf" class="text"  />'
				+ '</td>'
				+ '</tr>'
				+ '</table>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="4" valign="top"><table width="100%" cellpadding="0" cellspacing="0" border="0" id="info_tables2">'
				+ '<tr>'
				+ '<td width="75" rowspan="14"><strong>生活方式</strong></td>'
				+ '<td colspan="2" rowspan="3"><strong>体育锻炼</strong></td>'
				+ '<td width="143"><font color="#FF0000"><strong>锻炼频率</strong></font></td>'
				+ '<td colspan="3">' 
				+ '<input id="physicalExerciseFrequency_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="physicalExerciseFrequency" value="1" />每天&nbsp;&nbsp;'
				+ '<input id="physicalExerciseFrequency_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="physicalExerciseFrequency" value="2" />每周一次以上&nbsp;&nbsp;'
				+ '<input id="physicalExerciseFrequency_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="physicalExerciseFrequency" value="3" />偶尔&nbsp;&nbsp;'
				+ '<input id="physicalExerciseFrequency_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="physicalExerciseFrequency" value="4" />不锻炼&nbsp;&nbsp;'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td ><font color="#FF0000"><strong>每次锻炼时间</strong></font></td>'
				+ '<td width="143" ><input id="everyPhysicalExerciseTime'+this.idPostfix+'" type="text" name="everyPhysicalExerciseTime" class="widt80"  />分钟</td>'
				+ '<td width="143" ><font color="#FF0000"><strong>坚持锻炼时间</strong></font></td>'
				+ '<td width="143"><input id="insistexercisetime'+this.idPostfix+'" type="text" name="insistexercisetime" class="widt80"  />年</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>锻炼方式</strong></font></td>'
				+ '<td colspan="3"><input id="exerciseStyle'+this.idPostfix+'" type="text" name="exerciseStyle"  class="widtP90"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  colspan="2"><font color="#FF0000"><strong>饮食习惯</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="dietaryHabit_1'+this.idPostfix+'" type="checkbox" name="dietaryHabit" value="1" />1荤素均衡&nbsp;&nbsp;'
				+ '<input id="dietaryHabit_2'+this.idPostfix+'" type="checkbox" name="dietaryHabit" value="2" />2荤食为主&nbsp;&nbsp;'
				+ '<input id="dietaryHabit_3'+this.idPostfix+'" type="checkbox" name="dietaryHabit" value="3" />3素食为主&nbsp;&nbsp;'
				+ '<input id="dietaryHabit_4'+this.idPostfix+'" type="checkbox" name="dietaryHabit" value="4" />4嗜盐&nbsp;&nbsp;'
				+ '<input id="dietaryHabit_5'+this.idPostfix+'" type="checkbox" name="dietaryHabit" value="5" />5嗜油&nbsp;&nbsp;'
				+ '<input id="dietaryHabit_6'+this.idPostfix+'" type="checkbox" name="dietaryHabit" value="6" />6嗜糖&nbsp;&nbsp;'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="3"  colspan="2"><strong>吸烟情况</strong></td>'
				+ '<td><font color="#FF0000"><strong>吸烟状况</strong></font></td>'
				+ '<td colspan="3">' 
				+ '<input id="wehtherSmoke_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="wehtherSmoke" value="1" />从不吸烟&nbsp;&nbsp;'
				+ '<input id="wehtherSmoke_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="wehtherSmoke" value="2" />已戒烟&nbsp;&nbsp;'
				+ '<input id="wehtherSmoke_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="wehtherSmoke" value="3" />吸烟&nbsp;&nbsp;'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>日吸烟量</strong></font></td>'
				+ '<td colspan="3">平均'
				+ '<input id="smokes'+this.idPostfix+'" type="text" name="smokes" class="widt80"  />支'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>开始吸烟年龄</strong></font></td>'
				+ '<td><input id="beginSmokeTime'+this.idPostfix+'" type="text" name="beginSmokeTime" class="widt80"  />岁</td>'
				+ '<td><strong>戒烟年龄</strong></td>'
				+ '<td><input id="stopSmokeTime'+this.idPostfix+'" type="text" name="stopSmokeTime" class="widt80"  />岁</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="5"  colspan="2"><strong>饮酒情况</strong></td>'
				+ '<td><font color="#FF0000"><strong>饮酒频率</strong></font></td>'
				+ '<td colspan="3">' 
				+ '<input id="drinkingFrequency_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="drinkingFrequency" value="1" />从不&nbsp;&nbsp;'
				+ '<input id="drinkingFrequency_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="drinkingFrequency" value="2" />偶尔&nbsp;&nbsp;'
				+ '<input id="drinkingFrequency_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="drinkingFrequency" value="3" />经常&nbsp;&nbsp;'
				+ '<input id="drinkingFrequency_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="drinkingFrequency" value="4" />每天&nbsp;&nbsp;'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>日饮酒量</strong></font></td>'
				+ '<td colspan="3">平均'
				+ '<input id="alcoholConsumption'+this.idPostfix+'" type="text" name="alcoholConsumption" class="widt80"  />两'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>是否戒酒</strong></font></td>'
				+ '<td colspan="3">' 
				+ '<input id="whetherDrink_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="whetherDrink" value="1" />未戒酒&nbsp;'
				+ '<input id="whetherDrink_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="whetherDrink" value="2" />已戒酒' 
				+ '，戒酒年龄：<input id="stopDrinkingTime'+this.idPostfix+'" type="text" name="stopDrinkingTime" class="widt80"  />岁'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>开始饮酒年龄</strong></font></td>'
				+ '<td><input id="geginToDrinkTime'+this.idPostfix+'" type="text" name="geginToDrinkTime" class="widt80"  />岁</td>'
				+ '<td><font color="#FF0000">近一年内是否曾醉酒</font></td>'
				+ '<td>' 
				+ '<input id="isDrink_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="isDrink" value="1" />是'
				+ '<input id="isDrink_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="isDrink" value="2" />否'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>饮酒种类</strong></font></td>'
				+ '<td colspan="3">' 
				+ '<input id="mainDrinkingVvarieties_1'+this.idPostfix+'" type="checkbox" name="mainDrinkingVvarieties" value="1" />1白酒&nbsp;'
				+ '<input id="mainDrinkingVvarieties_2'+this.idPostfix+'" type="checkbox" name="mainDrinkingVvarieties" value="3" />2啤酒&nbsp;'
				+ '<input id="mainDrinkingVvarieties_3'+this.idPostfix+'" type="checkbox" name="mainDrinkingVvarieties" value="5" />3红酒&nbsp;'
				+ '<input id="mainDrinkingVvarieties_4'+this.idPostfix+'" type="checkbox" name="mainDrinkingVvarieties" value="4" />4黄酒&nbsp;'
				+ '<input id="mainDrinkingVvarieties_9'+this.idPostfix+'" type="checkbox" name="mainDrinkingVvarieties" value="9" />5其他'
				+ '<input id="drinkOther'+this.idPostfix+'" type="text" name="drinkOther" class="widt160"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="2"  colspan="2"><font color="#FF0000"><strong>职业病危害因素接触史</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="occupational_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="occupational" value="1"/>无'
				+ '<input id="occupational_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="occupational" value="2"/>有'
				+ '（工种<input id="jobs'+this.idPostfix+'" type="text" name="jobs" class="widt300"/>'
				+ '从业时间年<input id="workTime'+this.idPostfix+'" type="text" name="workTime" class="widt80"  />） '
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="4">粉&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;尘 <input id="dust'+this.idPostfix+'" type="text" name="dust" class="widt120"  /> 防护措施'
				+ '<input id="dustPro_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dustPro" value="1"/>无'
				+ '<input id="dustPro_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dustPro" value="2"/>有'
				+ '<input id="dustProDesc'+this.idPostfix+'" type="text" name="dustProDesc" class="widt280"  />'
				+ '<br />'
				+ '放射物质<input id="ray'+this.idPostfix+'" type="text" name="ray" class="widt120"  /> 防护措施'
				+ '<input id="rayPro_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rayPro" value="1"/>无'
				+ '<input id="rayPro_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rayPro" value="2"/>有'
				+ '<input id="rayProDesc'+this.idPostfix+'" type="text" name="rayProDesc" class="widt280"  />'
				+ '<br />'
				+ '物理因素<input id="physicalFactor'+this.idPostfix+'" type="text" name="physicalFactor" class="widt120"  /> 防护措施'
				+ '<input id="physicalFactorPro_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="physicalFactorPro" value="1"/>无'
				+ '<input id="physicalFactorPro_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="physicalFactorPro" value="2"/>有'
				+ '<input id="physicalFactorProDesc'+this.idPostfix+'" type="text" name="physicalFactorProDesc" class="widt280"  />'
				+ '<br />'
				+ '化学物质<input id="chemicals'+this.idPostfix+'" type="text" name="chemicals" class="widt120"  /> 防护措施'
				+ '<input id="chemicalsPro_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="chemicalsPro" value="1" />无'
				+ '<input id="chemicalsPro_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="chemicalsPro" value="2" />有'
				+ '<input id="chemicalsProDesc'+this.idPostfix+'" type="text" name="chemicalsProDesc" class="widt280"  />'
				+ '<br />'
				+ '其&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;他 <input id="other'+this.idPostfix+'" type="text" name="other" class="widt120"  /> 防护措施'
				+ '<input id="otherPro_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="otherPro" value="1" />无'
				+ '<input id="otherPro_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="otherPro" value="2" />有'
				+ '<input id="otherProDesc'+this.idPostfix+'" type="text" name="otherProDesc" class="widt280"  />'
				+ '<br /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="4"><strong>脏器功能</strong></td>'
				+ '<td colspan="2"><strong>口   腔</strong></td>'
				+ '<td colspan="4"><font color="#FF0000">口唇：</font>'
				+ '<input id="lip_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lip" value="1" />红润&nbsp;&nbsp;'
				+ '<input id="lip_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lip" value="2" />苍白&nbsp;&nbsp;'
				+ '<input id="lip_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lip" value="3" />发绀&nbsp;&nbsp;'
				+ '<input id="lip_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lip" value="4" />皲裂&nbsp;&nbsp;'
				+ '<input id="lip_5'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lip" value="5" />疱疹&nbsp;&nbsp;' 
				+ '<br />'
				+ '<font color="#FF0000">齿列：</font>' 
				+ '<input id="denture_1'+this.idPostfix+'" type="checkbox" onclick="onDentureChange(value)" name="denture" value="1" />正常&nbsp;&nbsp;'
				+ '<input id="denture_2'+this.idPostfix+'" type="checkbox" onclick="onDentureChange(value)" name="denture" value="2" />缺齿&nbsp;&nbsp;'
				+ '左上<input id="leftUp'+this.idPostfix+'" type="text" name="leftUp" size="4"/>'
				+ '左下<input id="leftDown'+this.idPostfix+'" type="text" name="leftDown" size="4"/>'
				+ '/右上<input id="rightUp'+this.idPostfix+'" type="text" name="rightUp" size="4"/>'
				+ '右下<input id="rightDown'+this.idPostfix+'" type="text" name="rightDown" size="4"/>'
				+ '<br />'
				+ '<input id="denture_3'+this.idPostfix+'" type="checkbox" onclick="onDentureChange(value)" name="denture" value="3" />龋齿&nbsp;&nbsp;'
				+ '左上<input id="leftUp2'+this.idPostfix+'" type="text" name="leftUp2" size="4"/>'
				+ '左下<input id="leftDown2'+this.idPostfix+'" type="text" name="leftDown2" size="4"/>'
				+ '/右上<input id="rightUp2'+this.idPostfix+'" type="text" name="rightUp2" size="4"/>'
				+ '右下<input id="rightDown2'+this.idPostfix+'" type="text" name="rightDown2" size="4"/>'
				+ '<br />'
				+ '<input id="denture_4'+this.idPostfix+'" type="checkbox" onclick="onDentureChange(value)" name="denture" value="4" />义齿(假牙)&nbsp;'
				+ '左上<input id="leftUp3'+this.idPostfix+'" type="text" name="leftUp3" size="4"/>'
				+ '左下<input id="leftDown3'+this.idPostfix+'" type="text" name="leftDown3" size="4"/>'
				+ '/右上<input id="rightUp3'+this.idPostfix+'" type="text" name="rightUp3" size="4"/>'
				+ '右下<input id="rightDown3'+this.idPostfix+'" type="text" name="rightDown3" size="4"/>'
				+ '<br />'
				+ '<font color="#FF0000">咽部：</font>'
				+ '<input id="pharyngeal_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="pharyngeal" value="1" />无充血&nbsp;&nbsp;'
				+ '<input id="pharyngeal_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="pharyngeal" value="2" />充血&nbsp;&nbsp;'
				+ '<input id="pharyngeal_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="pharyngeal" value="3" />淋巴滤泡增生&nbsp;&nbsp;'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  colspan="2"><strong>视   力</strong></td>'
				+ '<td colspan="4"><font color="#FF0000"> 左眼</font><input id="leftEye'+this.idPostfix+'" type="text" name="leftEye" class="widt80"  />'
				+ '&nbsp;&nbsp;<font color="#FF0000">右眼</font><input id="rightEye'+this.idPostfix+'" type="text" name="rightEye" class="widt80"  />'
				+ '<font color="#FF0000">（矫正视力：左眼</font><input id="recLeftEye'+this.idPostfix+'" type="text" name="recLeftEye" class="widt80"  />'
				+ '&nbsp;&nbsp;<font color="#FF0000">右眼</font><input id="recRightEye'+this.idPostfix+'" type="text" name="recRightEye" class="widt80"  />） '
				+ ' </td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  colspan="2"><font color="#FF0000"><strong>听   力</strong></font></td>'
				+ '<td colspan="4">' 
				+	'<input id="hearing_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="hearing" value="1" />听见&nbsp;&nbsp;'
				+ '<input id="hearing_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="hearing" value="2" />听不清或无法听见 '
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td  colspan="2"><font color="#FF0000"><strong>运动功能</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="motion_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="motion" value="1" />可顺利完成&nbsp;&nbsp;'
				+ '<input id="motion_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="motion" value="2" />无法独立完成其中任何一个动作 ' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="19"><strong>查体</strong></td>'
				+ '<td colspan="2" ><strong>眼底*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="fundus_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="fundus" value="1" />正常&nbsp;&nbsp;'
				+ '<input id="fundus_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="fundus" value="2" />异常'
				+ '<input id="fundusDesc'+this.idPostfix+'" type="text" name="fundusDesc" class="widtP80"/>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>皮     肤</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="skin_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="skin" value="1" />正常&nbsp;&nbsp;'
				+ '<input id="skin_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="skin" value="2" />潮红&nbsp;&nbsp;'
				+ '<input id="skin_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="skin" value="3" />苍白&nbsp;&nbsp;'
				+ '<input id="skin_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="skin" value="4" />发绀&nbsp;&nbsp;'
				+ '<input id="skin_5'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="skin" value="5" />黄染&nbsp;&nbsp;'
				+ '<input id="skin_6'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="skin" value="6" />色素沉着&nbsp;&nbsp;'
				+ '<input id="skin_7'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="skin" value="7" />其他'
				+ '<input id="skinDesc'+this.idPostfix+'" type="text" name="skinDesc" class="widt195"/>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>巩     膜</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="sclera_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="sclera" value="1" />正常&nbsp;&nbsp;'
				+ '<input id="sclera_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="sclera" value="2" />黄染&nbsp;&nbsp;'
				+ '<input id="sclera_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="sclera" value="3" />充血&nbsp;&nbsp;'
				+ '<input id="sclera_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="sclera" value="4" />其他'
				+ '<input id="scleraDesc'+this.idPostfix+'" type="text" name="scleraDesc" class="widt365"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>淋巴结</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="lymphnodes_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lymphnodes" value="1" />未触及&nbsp;&nbsp;'
				+ '<input id="lymphnodes_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lymphnodes" value="2" />锁骨上&nbsp;'
				+ '<input id="lymphnodes_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lymphnodes" value="3" />腋窝&nbsp;&nbsp;'
				+ '<input id="lymphnodes_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="lymphnodes" value="4" />其他'
				+ '<input id="lymphnodesDesc'+this.idPostfix+'" type="text" name="lymphnodesDesc" class="widt345"/>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="57" rowspan="3" align="center"><font color="#FF0000"><strong>肺</strong></font></td>'
				+ '<td width="81"><font color="#FF0000"><strong>桶状胸</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="barrelChest_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="barrelChest" value="1" />否&nbsp;&nbsp;'
				+ '<input id="barrelChest_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="barrelChest" value="2" />是'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>呼吸音</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="breathSound_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="breathSound" value="1" />正常&nbsp;&nbsp;'
				+ '<input id="breathSound_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="breathSound" value="2" />异常'
				+ '<input id="breathSoundDesc'+this.idPostfix+'" type="text" name="breathSoundDesc" class="widtP80"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>罗  音</strong></font></td>'
				+ '<td colspan="4">'
				+ '<input id="rales_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rales" value="1" />无&nbsp;&nbsp;'
				+ '<input id="rales_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rales" value="2" />干罗音&nbsp;&nbsp;'
				+ '<input id="rales_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rales" value="3" />湿罗音&nbsp;&nbsp;'
				+ '<input id="rales_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rales" value="4" />其他'
				+ '<input id="ralesDesc'+this.idPostfix+'" type="text" name="ralesDesc" class="widt315"/>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>心   脏</strong></td>'
				+ '<td colspan="4"><font color="#FF0000">心率</font>'
				+ '<input id="heartRate'+this.idPostfix+'" type="text" name="heartRate" class="widt80"  />次/分钟'
				+ '<br /><font color="#FF0000">心律：</font>'
				+	'<input id="rhythm_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rhythm" value="1" />齐&nbsp;&nbsp;'
				+ '<input id="rhythm_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rhythm" value="2" />不齐&nbsp;&nbsp;'
				+ '<input id="rhythm_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="rhythm" value="3" />绝对不齐'
				+ '<br /><font color="#FF0000">杂音：</font>' 
				+ '<input id="heartMurmur_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="heartMurmur" value="1" />无&nbsp;&nbsp;'
				+ '<input id="heartMurmur_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="heartMurmur" value="2" />有'
				+ '<input id="heartMurmurDesc'+this.idPostfix+'" type="text" name="heartMurmurDesc" class="widt450"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>腹   部</strong></font></td>'
				+ '<td colspan="4"><font color="#FF0000">压痛：</font>'
				+ '<input id="abdominAltend_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="abdominAltend" value="1" />无&nbsp;&nbsp;'
				+ '<input id="abdominAltend_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="abdominAltend" value="2" />有'
				+ '<input id="abdominAltendDesc'+this.idPostfix+'" type="text" name="abdominAltendDesc" class="widt450"  />'
				+ '<br />'
				+ '<font color="#FF0000">包块：</font>' 
				+ '<input id="adbominAlmass_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="adbominAlmass" value="1" />无&nbsp;&nbsp;'
				+ '<input id="adbominAlmass_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="adbominAlmass" value="2" />有'
				+ '<input id="adbominAlmassDesc'+this.idPostfix+'" type="text" name="adbominAlmassDesc" class="widt450"  />'
				+ '<br />'
				+ '<font color="#FF0000">肝大：</font>' 
				+ '<input id="liverBig_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="liverBig" value="1" />无&nbsp;&nbsp;'
				+ '<input id="liverBig_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="liverBig" value="2" />有'
				+ '<input id="liverBigDesc'+this.idPostfix+'" type="text" name="liverBigDesc" class="widt450"  />'
				+ '<br />'
				+ '<font color="#FF0000">脾大：</font>'
				+ '<input id="splenomegaly_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="splenomegaly" value="1" />无&nbsp;&nbsp;'
				+ '<input id="splenomegaly_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="splenomegaly" value="2" />有'
				+ '<input id="splenomegalyDesc'+this.idPostfix+'" type="text" name="splenomegalyDesc" class="widt450"  />'
				+ '<br />'
				+ '<font color="#FF0000">移动性浊音：</font>'
				+ '<input id="dullness_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dullness" value="1" />无'
				+ '<input id="dullness_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dullness" value="2" />有'
				+ '<input id="dullnessDesc'+this.idPostfix+'" type="text" name="dullnessDesc" class="widt420"  />'
				+ '<br />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>下肢水肿</strong></font></td>'
				+ '<td colspan="4">'
				+ '<input id="edema_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="edema" value="1" />无&nbsp;&nbsp;'
				+ '<input id="edema_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="edema" value="2" />单侧&nbsp;&nbsp;'
				+ '<input id="edema_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="edema" value="3" />双侧不对称&nbsp;&nbsp;'
				+ '<input id="edema_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="edema" value="4" /> 双侧对称'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>足背动脉搏动*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="footPulse_1'+this.idPostfix+'" type="checkbox" onclick="onFootPulseChange(value)"   name="footPulse" value="1" />未触及&nbsp;&nbsp;'
				+ '<input id="footPulse_2'+this.idPostfix+'" type="checkbox" onclick="onFootPulseChange(value)"  name="footPulse" value="2" />触及双侧对称&nbsp;&nbsp;'
				+ '<input id="footPulse_3'+this.idPostfix+'" type="checkbox" onclick="onFootPulseChange(value)"  name="footPulse" value="3" />触及左侧弱或消失&nbsp;&nbsp;'
				+ '<input id="footPulse_4'+this.idPostfix+'" type="checkbox" onclick="onFootPulseChange(value)"  name="footPulse" value="4" />触及右侧弱或消失'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>肛门指诊*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="dre_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dre" value="1" />未及异常&nbsp;&nbsp;'
				+ '<input id="dre_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dre" value="2" />触痛&nbsp;&nbsp;'
				+ '<input id="dre_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dre" value="3" />包块&nbsp;&nbsp;'
				+ '<input id="dre_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dre" value="4" />前列腺异常&nbsp;'
				+ '<input id="dre_5'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="dre" value="5" /> 其他'
				+ '<input id="dreDesc'+this.idPostfix+'" type="text" name="dreDesc" class="widt250"/>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>乳腺*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="breast_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="breast" value="1" />未见异常&nbsp;&nbsp;'
				+ '<input id="breast_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="breast" value="2" />乳房切除&nbsp;&nbsp;'
				+ '<input id="breast_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="breast" value="3" />异常泌乳&nbsp;&nbsp;'
				+ '<input id="breast_4'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="breast" value="4" />乳腺包块&nbsp;&nbsp;'
				+ '<input id="breast_7'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="breast" value="7" />其他'
				+ '<input id="breastDesc'+this.idPostfix+'" type="text" name="breastDesc"  class="widt215"/>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="5"><strong>妇科*</strong></td>'
				+ '<td><strong>外阴</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="vulva_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="vulva" value="1" />未见异常&nbsp;&nbsp;'
				+ '<input id="vulva_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="vulva" value="2" />异常' 
				+ '<input id="vulvaDesc'+this.idPostfix+'" type="text" name="vulvaDesc" class="widt435"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>阴道</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="vaginal_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="vaginal" value="1" />未见异常&nbsp;&nbsp;'
				+ '<input id="vaginal_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="vaginal" value="2" />异常'
				+ '<input id="vaginalDesc'+this.idPostfix+'" type="text" name="vaginalDesc" class="widt435"  />' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>宫颈</strong></td>'
				+ '<td colspan="4">' 
				+	'<input id="cervix_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="cervix" value="1" />未见异常&nbsp;&nbsp;'
				+ '<input id="cervix_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="cervix" value="2" />异常'
				+ '<input id="cervixDesc'+this.idPostfix+'" type="text" name="cervixDesc" class="widt435"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>宫体</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="palace_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="palace" value="1" />未见异常&nbsp;&nbsp;'
				+ '<input id="palace_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="palace" value="2" />异常'
				+ '<input id="palaceDesc'+this.idPostfix+'" type="text" name="palaceDesc" class="widt435"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>附件</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="attachment_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="attachment" value="1" />未见异常&nbsp;&nbsp;'
				+ '<input id="attachment_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="attachment" value="2" />异常'
				+ '<input id="attachmentDesc'+this.idPostfix+'" type="text" name="attachmentDesc" class="widt435"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>其   他*</strong></td>'
				+ '<td colspan="4"><input id="tjother'+this.idPostfix+'" type="text" name="tjother" class="input_btline widtP97"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="15"><strong>辅助检查</strong></td>'
				+ '<td colspan="2"><strong>血常规*</strong></td>'
				+ '<td colspan="4">' 
				+ '血红蛋白<input id="hgb'+this.idPostfix+'" type="text" name="hgb" class="input_btline widt80"  />g/L  '
				+ '白细胞<input id="wbc'+this.idPostfix+'" type="text" name="wbc" class="input_btline widt80"  />×10<sup>9</sup></laber>/L '
				+ '血小板<input id="platelet'+this.idPostfix+'" type="text" name="platelet" class="input_btline widt80"  />×10<sup>9</sup>/L '
				+ '<input id="xjc_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"   name="xjc" value="1" />拒测'
				+ '<br/>其他<input id="bloodOther'+this.idPostfix+'" type="text" name="bloodOther" class="input_btline widtP95"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>尿常规*</strong></td>'
				+ '<td colspan="4">'
				+ '尿蛋白<input id="proteinuria'+this.idPostfix+'" type="text" name="proteinuria" class="input_btline widt80"  />'
				+ '尿糖<input id="glu'+this.idPostfix+'" type="text" name="glu" class="input_btline widt80"  />'
				+ '尿酮体<input id="dka'+this.idPostfix+'" type="text" name="dka" class="input_btline widt80"  />'
				+ '尿潜血<input id="oc'+this.idPostfix+'" type="text" name="oc" class="input_btline widt80"  />'
				+ '尿白细胞<input id="leu'+this.idPostfix+'" type="text" name="leu" class="input_btline widt80"  />'
				+ '其他<input id="urineOther'+this.idPostfix+'" type="text" name="urineOther" class="input_btline widt80"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>空腹血糖*</strong></td>'
				+ '<td colspan="4"><input id="fbs'+this.idPostfix+'" type="text" name="fbs" class="input_btline widt80"  />mmol/L或'
				+ '<input id="fbs2'+this.idPostfix+'" type="text" name="fbs2" class="input_btline widt80"  />mg/dL'
				+ '               随机血糖<input id="fbs3'+this.idPostfix+'" type="text" name="fbs3" class="input_btline widt80"  />mmol/L'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>心电图*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="ecg_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="ecg" value="1" />正常'
				+ '<input id="ecg_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="ecg" value="2" />异常'
				+ '<input id="ecgText'+this.idPostfix+'" type="text" name="ecgText" class="widt450"  />'
				+ '<input id="ecg_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="ecg" value="3" />拒测'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>尿微量白蛋白*</strong></td>'
				+ '<td colspan="4"><input id="malb'+this.idPostfix+'" type="text" name="malb" class="input_btline widt80"  />mg/dL'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>大便潜血*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="fob_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="fob" value="1" />阴性'
				+ '<input id="fob_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="fob" value="2" style="margin-left:20px;"/>阳性'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>糖化血红蛋白*</strong></td>'
				+ '<td colspan="4"><input id="hba1c'+this.idPostfix+'" type="text" name="hba1c" class="input_btline widt80"  />%</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>乙型肝炎表面抗原*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="hbsag_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="hbsag" value="1" />阴性'
				+ '<input id="hbsag_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="hbsag" value="2" style="margin-left:20px;"/>阳性'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>肝功能*</strong></td>'
				+ '<td colspan="4">血清谷丙转氨酶'
				+ '<input id="alt'+this.idPostfix+'" type="text" name="alt" class="input_btline widt80"  />'
				+ 'U/L       血清谷草转氨酶'
				+ '<input id="ast'+this.idPostfix+'" type="text" name="ast" class="input_btline widt80"  />U/L'
				+ '白蛋白<input id="alb'+this.idPostfix+'" type="text" name="alb" class="input_btline widt80"  />g/L '
				+ '<br />'
				+ '总胆红素<input id="tbil'+this.idPostfix+'" type="text" name="tbil" class="input_btline widt80"  />μmol/L'
				+ '结合胆红素<input id="dbil'+this.idPostfix+'" type="text" name="dbil" class="input_btline widt80"  />μmol/L '
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>肾功能*</strong></td>'
				+ '<td colspan="4">'
				+ '血清肌酐<input id="cr'+this.idPostfix+'" type="text" name="cr" class="input_btline widt80"  />μmol/L     '
				+ '血尿素氮<input id="bun'+this.idPostfix+'" type="text" name="bun" class="input_btline widt80"  />mmol/L<br />'
				+ '血钾浓度<input id="kalemia'+this.idPostfix+'" type="text" name="kalemia" class="input_btline widt80"  />mmol/L     '
				+ '血钠浓度<input id="natremia'+this.idPostfix+'" type="text" name="natremia" class="input_btline widt80"  />mmol/L'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>血   脂*</strong></td>'
				+ '<td colspan="4">' 
				+ '总胆固醇<input id="tc'+this.idPostfix+'" type="text" name="tc" class="input_btline widt80"  />mmol/L <br />'
				+ '甘油三酯<input id="tg'+this.idPostfix+'" type="text" name="tg" class="input_btline widt80"  />mmol/L<br />'
				+ '血清低密度脂蛋白胆固醇<input id="ldl'+this.idPostfix+'" type="text" name="ldl" class="input_btline widt80"  />mmol/L<br />'
				+ '血清高密度脂蛋白胆固醇<input id="hdl'+this.idPostfix+'" type="text" name="hdl" class="input_btline widt80"  />mmol/L '
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>胸部X线片*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="x_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="x" value="1" />正常'
				+ '<input id="x_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="x" value="2" />异常'
				+ '<input id="xText'+this.idPostfix+'" type="text" name="xText" class="widt480"  />'

				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>B   超*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="b_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="b" value="1" />正常'
				+ '<input id="b_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="b" value="2" />异常'
				+ '<input id="bText'+this.idPostfix+'" type="text" name="bText" class="widt450"  />'
				+ '<input id="b_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="b" value="3" />拒测'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>宫颈涂片*</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="ps_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="ps" value="1" />正常'
				+ '<input id="ps_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="ps" value="2" />异常'
				+ '<input id="psText'+this.idPostfix+'" type="text" name="psText" class="widt480"  /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>备注*</strong></td>'
				+ '<td colspan="4"><input id="fuOther'+this.idPostfix+'" type="text" name="fuOther" class="input_btline widtP97"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>其他*</strong></td>'
				+ '<td colspan="4"><input id="fuOther1'+this.idPostfix+'" type="text" name="fuOther1" class="input_btline widtP97"/></td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td rowspan="9"><strong>中医体质辨识*</strong></td>'
				+ '<td colspan="2"><strong>平和质</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="recognize1_11'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize1" value="11" />是'
				+ '<input id="recognize1_12'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize1" value="12" style="margin-left:20px;"/>基本是'
				+ '</td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td colspan="2"><strong>气虚质</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="recognize2_21'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize2" value="21" />是'
				+ '<input id="recognize2_22'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize2" value="22" style="margin-left:20px;"/>倾向是'
				+ '</td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td colspan="2"><strong>阳虚质</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="recognize3_31'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize3" value="31" />是'
				+ '<input id="recognize3_32'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize3" value="32" style="margin-left:20px;"/>倾向是'
				+ '</td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td colspan="2"><strong>阴虚质</strong></td>'
				+ '<td colspan="4">' 
				+ '<input id="recognize4_41'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize4" value="41" />是'
				+ '<input id="recognize4_42'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize4" value="42" style="margin-left:20px;"/>倾向是'
				+ '</td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td colspan="2"><strong>痰湿质</strong></td>'
				+ '<td colspan="4">'
				+ '<input id="recognize5_51'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize5" value="51" />是'
				+ '<input id="recognize5_52'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize5" value="52" style="margin-left:20px;"/>倾向是'
				+ '</td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td colspan="2"><strong>湿热质</strong></td>'
				+ '<td colspan="4">'
				+ '<input id="recognize6_61'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize6" value="61" />是'
				+ '<input id="recognize6_62'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize6" value="62" style="margin-left:20px;"/>倾向是'
				+ '</td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td colspan="2"><strong>血瘀质</strong></td>'
				+ '<td colspan="4">'
				+ '<input id="recognize7_71'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize7" value="71" />是'
				+ '<input id="recognize7_72'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize7" value="72" style="margin-left:20px;"/>倾向是'
				+ '</td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td colspan="2"><strong>气郁质</strong></td>'
				+ '<td colspan="4">'
				+ '<input id="recognize8_81'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize8" value="81" />是'
				+ '<input id="recognize8_82'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize8" value="82" style="margin-left:20px;"/>倾向是'
				+ '</td>'
				+ '</tr>'
				+ '<tr hidden="true">'
				+ '<td colspan="2"><strong>特秉质</strong></td>'
				+ '<td colspan="4">'
				+ '<input id="recognize9_91'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize9" value="91" />是'
				+ '<input id="recognize9_92'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="recognize9" value="92" style="margin-left:20px;"/>倾向是'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="7"><strong>现存主要健康问题</strong></td>'
				+ '<td colspan="2"><font color="#FF0000"><strong>脑血管疾病</strong></font></td>'
				+ '<td colspan="4">'
				+ '<input id="cerebrovascularDiseases_1'+this.idPostfix+'" type="checkbox" name="cerebrovascularDiseases" value="1" />1未发现'
				+ '<input id="cerebrovascularDiseases_2'+this.idPostfix+'" type="checkbox" name="cerebrovascularDiseases" value="2" />2缺血性卒中'
				+ '<input id="cerebrovascularDiseases_3'+this.idPostfix+'" type="checkbox" name="cerebrovascularDiseases" value="3" />3脑出血'
				+ '<input id="cerebrovascularDiseases_4'+this.idPostfix+'" type="checkbox" name="cerebrovascularDiseases" value="4" />4蛛网膜下腔出血'
				+ '<input id="cerebrovascularDiseases_5'+this.idPostfix+'" type="checkbox" name="cerebrovascularDiseases" value="5" />5短暂性脑缺血发作'
				+'<input id="cerebrovascularDiseases_6'+this.idPostfix+'" type="checkbox" name="cerebrovascularDiseases" value="6" />6其他'
				+ '<br/><input id="othercerebrovascularDiseases'+this.idPostfix+'" type="text" name="othercerebrovascularDiseases" class="widtP97"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>肾脏疾病</strong></font></td>'
				+ '<td colspan="4">'
				+ '<input id="kidneyDiseases_1'+this.idPostfix+'" type="checkbox" name="kidneyDiseases" value="1" />1未发现'
				+ '<input id="kidneyDiseases_2'+this.idPostfix+'" type="checkbox" name="kidneyDiseases" value="2" />2糖尿病肾病'
				+ '<input id="kidneyDiseases_3'+this.idPostfix+'" type="checkbox" name="kidneyDiseases" value="3" />3肾功能衰竭'
				+ '<input id="kidneyDiseases_4'+this.idPostfix+'" type="checkbox" name="kidneyDiseases" value="4" />4急性肾炎'
				+ '<input id="kidneyDiseases_5'+this.idPostfix+'" type="checkbox" name="kidneyDiseases" value="5" />5慢性肾炎'
				+ '<input id="kidneyDiseases_6'+this.idPostfix+'" type="checkbox" name="kidneyDiseases" value="6" />6其他'
				+ '<br/><input id="otherkidneyDiseases'+this.idPostfix+'" type="text" name="otherkidneyDiseases" class="widtP97"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>心脏疾病</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="heartDisease_1'+this.idPostfix+'" type="checkbox" name="heartDisease" value="1" />1未发现'
				+ '<input id="heartDisease_2'+this.idPostfix+'" type="checkbox" name="heartDisease" value="2" />2心肌梗死'
				+ '<input id="heartDisease_3'+this.idPostfix+'" type="checkbox" name="heartDisease" value="3" />3心绞痛'
				+ '<input id="heartDisease_4'+this.idPostfix+'" type="checkbox" name="heartDisease" value="4" />4冠状动脉血运重建'
				+ '<input id="heartDisease_5'+this.idPostfix+'" type="checkbox" name="heartDisease" value="5" />5充血性心力'
				+ '<input id="heartDisease_6'+this.idPostfix+'" type="checkbox" name="heartDisease" value="6" />6心前区疼痛'
				+ '<input id="heartDisease_7'+this.idPostfix+'" type="checkbox" name="heartDisease" value="7" />7其他'
				+ '<br/><input id="otherheartDisease'+this.idPostfix+'" name="otherheartDisease" type="text" class="widtP97"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>血管疾病</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="VascularDisease_1'+this.idPostfix+'" type="checkbox" name="VascularDisease" value="1" />1未发现'
				+ '<input id="VascularDisease_2'+this.idPostfix+'" type="checkbox" name="VascularDisease" value="2" />2夹层动脉瘤'
				+ '<input id="VascularDisease_3'+this.idPostfix+'" type="checkbox" name="VascularDisease" value="3" />3动脉闭塞性疾病'
				+ '<input id="VascularDisease_4'+this.idPostfix+'" type="checkbox" name="VascularDisease" value="4" />4其他'
				+ '<input id="otherVascularDisease'+this.idPostfix+'" type="text" name="otherVascularDisease" class="widt260"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>眼部疾病</strong></font></td>'
				+ '<td colspan="4">'
				+ '<input id="eyeDiseases_1'+this.idPostfix+'" type="checkbox" name="eyeDiseases" value="1" />1未发现'
				+ '<input id="eyeDiseases_2'+this.idPostfix+'" type="checkbox" name="eyeDiseases" value="2" />2视网膜出血或渗出'
				+ '<input id="eyeDiseases_3'+this.idPostfix+'" type="checkbox" name="eyeDiseases" value="3" />3视乳头水肿'
				+ '<input id="eyeDiseases_4'+this.idPostfix+'" type="checkbox" name="eyeDiseases" value="4" />4白内障'
				+ '<input id="eyeDiseases_5'+this.idPostfix+'" type="checkbox" name="eyeDiseases" value="5" />5其他'
				+ '<input id="othereyeDiseases'+this.idPostfix+'" type="text" name="othereyeDiseases" class="widt189"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>神经系统疾病</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="neurologicalDiseases_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="neurologicalDiseases" value="1" />未发现'
				+ '<input id="neurologicalDiseases_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="neurologicalDiseases" value="2" />有'
				+ '<input id="neurologicalDiseasesDesc'+this.idPostfix+'" type="text" name="neurologicalDiseasesDesc" class="widt480"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>其他系统疾病</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="otherDiseasesone_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="otherDiseasesone" value="1" />未发现'
				+ '<input id="otherDiseasesone_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="otherDiseasesone" value="2" />有'
				+ '<input id="otherDiseasesoneDesc'+this.idPostfix+'" type="text" name="otherDiseasesoneDesc" class="widt480"  />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="8"><strong>住院治疗情况</strong></td>'
				+ '<td colspan="2"><font color="#FF0000"><strong>住院情况</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="inhospitalFlag_y'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="inhospitalFlag" value="y" />有'
				+ '<input id="inhospitalFlag_n'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="inhospitalFlag" value="n" />无'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" rowspan="3"><strong>住院史</strong></td>'
				+ '<td align="center"><strong>入/出院日期</strong></td>'
				+ '<td align="center"><strong>原 因</strong></td>'
				+ '<td align="center"><strong>医疗机构名称</strong></td>'
				+ '<td align="center"><strong>病案号</strong></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><input id="situationId_1_1'+this.idPostfix+'" type="hidden"/><div id="inhospitalDate_1_1'+this.idPostfix+'"></div><div id="outhospitalDate_1_1'+this.idPostfix+'"></div></td>'
				+ '<td><input id="inhospitalReason_1_1'+this.idPostfix+'" type="text" name="inhospitalReason_1_1" size="16"/></td>'
				+ '<td><input id="medicalestablishmentName_1_1'+this.idPostfix+'" type="text" name="medicalestablishmentName_1_1" size="16"/></td>'
				+ '<td><input id="medicalrecordNumber_1_1'+this.idPostfix+'" type="text" name="medicalrecordNumber_1_1" size="16"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><input id="situationId_1_2'+this.idPostfix+'" type="hidden"/><div id="inhospitalDate_1_2'+this.idPostfix+'"></div><div id="outhospitalDate_1_2'+this.idPostfix+'"></div></td>'
				+ '<td><input id="inhospitalReason_1_2'+this.idPostfix+'" type="text" name="inhospitalReason_1_2" size="16"/></td>'
				+ '<td><input id="medicalestablishmentName_1_2'+this.idPostfix+'" type="text" name="medicalestablishmentName_1_2" size="16"/></td>'
				+ '<td><input id="medicalrecordNumber_1_2'+this.idPostfix+'" type="text" name="medicalrecordNumber_1_2" size="16"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><font color="#FF0000"><strong>家庭病床情况</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="infamilybedFlag_y'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="infamilybedFlag" value="y" />有'
				+ '<input id="infamilybedFlag_n'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="infamilybedFlag" value="n" />无'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" rowspan="3"><strong>家庭病床史</strong></td>'
				+ '<td align="center"><strong>建/撤床日期</strong></td>'
				+ '<td align="center"><strong>原 因</strong></td>'
				+ '<td align="center"><strong>医疗机构名称</strong></td>'
				+ '<td align="center"><strong>病案号</strong></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><input id="situationId_2_1'+this.idPostfix+'" type="hidden"/><div id="inhospitalDate_2_1'+this.idPostfix+'"></div><div id="outhospitalDate_2_1'+this.idPostfix+'"></div></td>'
				+ '<td><input id="inhospitalReason_2_1'+this.idPostfix+'" type="text" name="inhospitalReason_2_1" size="16"/></td>'
				+ '<td><input id="medicalestablishmentName_2_1'+this.idPostfix+'" type="text" name="medicalestablishmentName_2_1" size="16"/></td>'
				+ '<td><input id="medicalrecordNumber_2_1'+this.idPostfix+'" type="text" name="medicalrecordNumber_2_1" size="16"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><input id="situationId_2_2'+this.idPostfix+'" type="hidden"/><div id="inhospitalDate_2_2'+this.idPostfix+'"></div><div id="outhospitalDate_2_2'+this.idPostfix+'"></div></td>'
				+ '<td><input id="inhospitalReason_2_2'+this.idPostfix+'" type="text" name="inhospitalReason_2_2" size="16"/></td>'
				+ '<td><input id="medicalestablishmentName_2_2'+this.idPostfix+'" type="text" name="medicalestablishmentName_2_2" size="16"/></td>'
				+ '<td><input id="medicalrecordNumber_2_2'+this.idPostfix+'" type="text" name="medicalrecordNumber_2_2" size="16"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="8"><strong>主要用药情况</strong></td>'
				+ '<td colspan="2"><font color="#FF0000"><strong>用药情况</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="medicineFlag_y'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineFlag" value="y" />有'
				+ '<input id="medicineFlag_n'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineFlag" value="n" />无'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>药物名称</strong></td>'
				+ '<td align="center"><strong>用法</strong></td>'
				+ '<td align="center"><strong>用量</strong></td>'
				+ '<td align="center"><strong>用药时间</strong></td>'
				+ '<td align="center"><strong>服药依从性</strong></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="situationId_1'+this.idPostfix+'" type="hidden" /><div id="div_medicine_1'+this.idPostfix+'" name="medicine_1"></div></td>'
				+ '<td><input id="use_1'+this.idPostfix+'" type="text" name="use_1" size="15"/></td>'
				+ '<td><input id="eachDose_1'+this.idPostfix+'" type="text" name="eachDose_1" size="15"/></td>'
				+ '<td><input id="useDate_1'+this.idPostfix+'" type="text" name="useDate_1" size="15"/></td>'
				+ '<td>'
				+'<input id="medicineYield1_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield1" value="1" />规律' 
				+'<input id="medicineYield1_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield1" value="2" />间断' 
				+'<input id="medicineYield1_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield1" value="3" />不服药' 
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="situationId_2'+this.idPostfix+'" type="hidden" /><div id="div_medicine_2'+this.idPostfix+'" name="medicine_2"></div></td>'
				+ '<td><input id="use_2'+this.idPostfix+'" type="text" name="use_2" size="15"/></td>'
				+ '<td><input id="eachDose_2'+this.idPostfix+'" type="text" name="eachDose_2" size="15"/></td>'
				+ '<td><input id="useDate_2'+this.idPostfix+'" type="text" name="useDate_2" size="15"/></td>'
				+ '<td>'
				+'<input id="medicineYield2_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield2" value="1" />规律' 
				+'<input id="medicineYield2_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield2" value="2" />间断' 
				+'<input id="medicineYield2_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield2" value="3" />不服药' 
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="situationId_3'+this.idPostfix+'" type="hidden" /><div id="div_medicine_3'+this.idPostfix+'" name="medicine_3"></div></td>'
				+ '<td><input id="use_3'+this.idPostfix+'" type="text" name="use_3" size="15"/></td>'
				+ '<td><input id="eachDose_3'+this.idPostfix+'" type="text" name="eachDose_3" size="15"/></td>'
				+ '<td><input id="useDate_3'+this.idPostfix+'" type="text" name="useDate_3" size="15"/></td>'
				+ '<td>'
				+'<input id="medicineYield3_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield3" value="1" />规律' 
				+'<input id="medicineYield3_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield3" value="2" />间断' 
				+'<input id="medicineYield3_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield3" value="3" />不服药' 
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="situationId_4'+this.idPostfix+'" type="hidden" /><div id="div_medicine_4'+this.idPostfix+'" name="medicine_4"></div></td>'
				+ '<td><input id="use_4'+this.idPostfix+'" type="text" name="use_4" size="15"/></td>'
				+ '<td><input id="eachDose_4'+this.idPostfix+'" type="text" name="eachDose_4" size="15"/></td>'
				+ '<td><input id="useDate_4'+this.idPostfix+'" type="text" name="useDate_4" size="15"/></td>'
				+ '<td>'
				+'<input id="medicineYield4_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield4" value="1" />规律' 
				+'<input id="medicineYield4_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield4" value="2" />间断' 
				+'<input id="medicineYield4_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield4" value="3" />不服药' 
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="situationId_5'+this.idPostfix+'" type="hidden" /><div id="div_medicine_5'+this.idPostfix+'" name="medicine_5"></div></td>'
				+ '<td><input id="use_5'+this.idPostfix+'" type="text" name="use_5" size="15"/></td>'
				+ '<td><input id="eachDose_5'+this.idPostfix+'" type="text" name="eachDose_5" size="15"/></td>'
				+ '<td><input id="useDate_5'+this.idPostfix+'" type="text" name="useDate_5" size="15"/></td>'
				+ '<td>'
				+'<input id="medicineYield5_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield5" value="1" />规律' 
				+'<input id="medicineYield5_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield5" value="2" />间断' 
				+'<input id="medicineYield5_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield5" value="3" />不服药' 
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="situationId_6'+this.idPostfix+'" type="hidden" /><div id="div_medicine_6'+this.idPostfix+'" name="medicine_6"></div></td>'
				+ '<td><input id="use_6'+this.idPostfix+'" type="text" name="use_6" size="15"/></td>'
				+ '<td><input id="eachDose_6'+this.idPostfix+'" type="text" name="eachDose_6" size="15"/></td>'
				+ '<td><input id="useDate_6'+this.idPostfix+'" type="text" name="useDate_6" size="15"/></td>'
				+ '<td>'
				+'<input id="medicineYield6_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield6" value="1" />规律' 
				+'<input id="medicineYield6_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield6" value="2" />间断' 
				+'<input id="medicineYield6_3'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="medicineYield6" value="3" />不服药' 
				+'</td>'
				+ '</tr>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="5"><strong>非免疫规划预防接种史</strong></td>'
				+ '<td colspan="2"><font color="#FF0000"><strong>接种情况</strong></font></td>'
				+ '<td colspan="4">' 
				+ '<input id="nonimmuneFlag_y'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="nonimmuneFlag" value="y" />有'
				+ '<input id="nonimmuneFlag_n'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="nonimmuneFlag" value="n" />无'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><strong>名称</strong></td>'
				+ '<td align="center"><strong>接种日期</strong></td>'
				+ '<td colspan="3" align="center"><strong>接种机构</strong></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="recordId_1'+this.idPostfix+'" type="hidden"/><input id="name_1'+this.idPostfix+'" type="text" name="name_1" size="15"/></td>'
				+ '<td><div id="inoculationDate_1'+this.idPostfix+'"><div></td>'
				+ '<td colspan="3"><input id="inoculationUnit_1'+this.idPostfix+'" type="text" name="inoculationUnit_1" class="text widtP98"  /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="recordId_2'+this.idPostfix+'" type="hidden"/><input id="name_2'+this.idPostfix+'" type="text" name="name_2" size="15"/></td>'
				+ '<td><div id="inoculationDate_2'+this.idPostfix+'"><div></td>'
				+ '<td colspan="3"><input id="inoculationUnit_2'+this.idPostfix+'" type="text" name="inoculationUnit_2" class="text widtP98"  /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2"><input id="recordId_3'+this.idPostfix+'" type="hidden"/><input id="name_3'+this.idPostfix+'" type="text" name="name_3" size="15"/></td>'
				+ '<td><div id="inoculationDate_3'+this.idPostfix+'"><div></td>'
				+ '<td colspan="3"><input id="inoculationUnit_3'+this.idPostfix+'" type="text" name="inoculationUnit_3" class="text widtP98"  /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>健康评价</strong></font></td>'
				+ '<td colspan="6">' 
				+ '<input id="abnormality_1'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="abnormality" value="1" />体检无异常' 
				+ '<input id="abnormality_2'+this.idPostfix+'" type="radio" ondblclick ="oncancel(id)"  name="abnormality" value="2" />有异常<br />'
				+ '异常1<input id="abnormality1'+this.idPostfix+'" type="text" name="abnormality1" class="input_btline widtP93"  /><br />'
				+ '异常2<input id="abnormality2'+this.idPostfix+'" type="text" name="abnormality2" class="input_btline widtP93"  /><br />'
				+ '异常3<input id="abnormality3'+this.idPostfix+'" type="text" name="abnormality3" class="input_btline widtP93"  /><br />'
				+ '异常4<input id="abnormality4'+this.idPostfix+'" type="text" name="abnormality4" class="input_btline widtP93" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><font color="#FF0000"><strong>健康指导</strong></font></td>'
				+ '<td colspan="3">' 
				+ '<input id="mana_1'+this.idPostfix+'" type="checkbox" name="mana" value="1" />1纳入慢性病患者健康管理<br />'
				+ '<input id="mana_2'+this.idPostfix+'" type="checkbox" name="mana" value="2" />2建议复查  '
				+ '<input id="mana_3'+this.idPostfix+'" type="checkbox" name="mana" value="3" />3建议转诊'
				+ '</td>'
				+ '<td colspan="3"><font color="#FF0000">危险因素控制：</font><br />' 
				+	'<input id="riskfactorsControl_1'+this.idPostfix+'" type="checkbox" name="riskfactorsControl" value="1" />1戒烟'
				+ '<input id="riskfactorsControl_2'+this.idPostfix+'" type="checkbox" name="riskfactorsControl" value="2" />2健康饮酒'
				+ '<input id="riskfactorsControl_3'+this.idPostfix+'" type="checkbox" name="riskfactorsControl" value="3" />3饮食'
				+ '<input id="riskfactorsControl_4'+this.idPostfix+'" type="checkbox" name="riskfactorsControl" value="4" />4锻炼'
				+ '<input id="riskfactorsControl_5'+this.idPostfix+'" type="checkbox" name="riskfactorsControl" value="5" />5减体重（目标'
				+	'<input id="targetWeight'+this.idPostfix+'" type="text" name="targetWeight"  class="widt80"/>kg）<br/>'
				+ '<input id="riskfactorsControl_6'+this.idPostfix+'" type="checkbox" name="riskfactorsControl" value="6" />6建议接种疫苗  '
				+ '<input id="vaccine'+this.idPostfix+'" type="text" name="vaccine"   class="widt120" />'
				+ '<input id="riskfactorsControl_7'+this.idPostfix+'" type="checkbox" name="riskfactorsControl" value="7" />7其他'
				+ '<input id="pjOther'+this.idPostfix+'" type="text" name="pjOther"   class="widt120"/>'
				+ '</td>'
				+'<input id="createUser'+this.idPostfix+'" name="createUser" type="hidden"/>'
				+'<input id="createUnit'+this.idPostfix+'" name="createUnit" type="hidden" />'
				+'<input id="createDate'+this.idPostfix+'" name="createDate" type="hidden" />'
				+'<input id="lastModifyUnit'+this.idPostfix+'" name="lastModifyUnit" type="hidden" />'
				+'<input id="lastModifyUser'+this.idPostfix+'" name="lastModifyUser" type="hidden" />'
				+'<input id="lastModifyDate'+this.idPostfix+'" name="lastModifyDate" type="hidden" />'
				+ '</tr>' + '</table></td>' + '</tr>' + '</table>';
		return html
	}
}