
package chis.jsdwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FamilyDoctorInterfaceServicePortType", targetNamespace = "http://webservice.server.familyDoctor.just.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FamilyDoctorInterfaceServicePortType {


    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.server.familyDoctor.just.com")
    @RequestWrapper(localName = "testinsert", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.Testinsert")
    @ResponseWrapper(localName = "testinsertResponse", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.TestinsertResponse")
    public String testinsert(
        @WebParam(name = "in0", targetNamespace = "http://webservice.server.familyDoctor.just.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.server.familyDoctor.just.com")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.server.familyDoctor.just.com")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.SendMessageResponse")
    public String sendMessage(
        @WebParam(name = "in0", targetNamespace = "http://webservice.server.familyDoctor.just.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.server.familyDoctor.just.com")
    @RequestWrapper(localName = "uploadSignInfo", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.UploadSignInfo")
    @ResponseWrapper(localName = "uploadSignInfoResponse", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.UploadSignInfoResponse")
    public String uploadSignInfo(
        @WebParam(name = "in0", targetNamespace = "http://webservice.server.familyDoctor.just.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.server.familyDoctor.just.com")
    @RequestWrapper(localName = "getFollowUpSurveryInfo", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.GetFollowUpSurveryInfo")
    @ResponseWrapper(localName = "getFollowUpSurveryInfoResponse", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.GetFollowUpSurveryInfoResponse")
    public String getFollowUpSurveryInfo(
        @WebParam(name = "in0", targetNamespace = "http://webservice.server.familyDoctor.just.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.server.familyDoctor.just.com")
    @RequestWrapper(localName = "getSignInfo", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.GetSignInfo")
    @ResponseWrapper(localName = "getSignInfoResponse", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.GetSignInfoResponse")
    public String getSignInfo(
        @WebParam(name = "in0", targetNamespace = "http://webservice.server.familyDoctor.just.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.server.familyDoctor.just.com")
    @RequestWrapper(localName = "getWDDataInfos", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.GetWDDataInfos")
    @ResponseWrapper(localName = "getWDDataInfosResponse", targetNamespace = "http://webservice.server.familyDoctor.just.com", className = "jsdwebservice.GetWDDataInfosResponse")
    public String getWDDataInfos(
        @WebParam(name = "in0", targetNamespace = "http://webservice.server.familyDoctor.just.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.server.familyDoctor.just.com")
        String in1);

}
