
package chis.jsdwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FamilyDoctorInterfaceService", targetNamespace = "http://webservice.server.familyDoctor.just.com", wsdlLocation = "http://12.43.53.4:7080/FamilyDoctorInterface/services/FamilyDoctorInterfaceService?wsdl")
public class FamilyDoctorInterfaceService
    extends Service
{

    private final static URL FAMILYDOCTORINTERFACESERVICE_WSDL_LOCATION;
    private final static WebServiceException FAMILYDOCTORINTERFACESERVICE_EXCEPTION;
    private final static QName FAMILYDOCTORINTERFACESERVICE_QNAME = new QName("http://webservice.server.familyDoctor.just.com", "FamilyDoctorInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://12.43.53.4:7080/FamilyDoctorInterface/services/FamilyDoctorInterfaceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FAMILYDOCTORINTERFACESERVICE_WSDL_LOCATION = url;
        FAMILYDOCTORINTERFACESERVICE_EXCEPTION = e;
    }

    public FamilyDoctorInterfaceService() {
        super(__getWsdlLocation(), FAMILYDOCTORINTERFACESERVICE_QNAME);
    }

    public FamilyDoctorInterfaceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FAMILYDOCTORINTERFACESERVICE_QNAME, features);
    }

    public FamilyDoctorInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, FAMILYDOCTORINTERFACESERVICE_QNAME);
    }

    public FamilyDoctorInterfaceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FAMILYDOCTORINTERFACESERVICE_QNAME, features);
    }

    public FamilyDoctorInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FamilyDoctorInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FamilyDoctorInterfaceServicePortType
     */
    @WebEndpoint(name = "FamilyDoctorInterfaceServiceHttpPort")
    public FamilyDoctorInterfaceServicePortType getFamilyDoctorInterfaceServiceHttpPort() {
        return super.getPort(new QName("http://webservice.server.familyDoctor.just.com", "FamilyDoctorInterfaceServiceHttpPort"), FamilyDoctorInterfaceServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FamilyDoctorInterfaceServicePortType
     */
    @WebEndpoint(name = "FamilyDoctorInterfaceServiceHttpPort")
    public FamilyDoctorInterfaceServicePortType getFamilyDoctorInterfaceServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.server.familyDoctor.just.com", "FamilyDoctorInterfaceServiceHttpPort"), FamilyDoctorInterfaceServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FAMILYDOCTORINTERFACESERVICE_EXCEPTION!= null) {
            throw FAMILYDOCTORINTERFACESERVICE_EXCEPTION;
        }
        return FAMILYDOCTORINTERFACESERVICE_WSDL_LOCATION;
    }

}
