$package("chis.application.psy.script.html");

chis.application.psy.script.html.PsychosisVisitHtmlTemplate = {
	PsychosisVisitMedicineList : [
		{id:'recordId',type:'hidden'},
		{id:'visitId',type:'hidden'},
		{id:'medicineName',type:'div'},
		{id:'medicineFrequency',type:'text'},
		{id:'days',type:'hidden'},
		{id:'medicineDosage',type:'text'},
		{id:'medicineUnit',type:'text'}
	],
	getPsyVisitHTMLTemplate : function() {
		var html = '<div class="my">'
				+ '<input id="visitId'+this.idPostfix+'" name="visitId" type="hidden" title="随访ID"/>'
				+ '<input id="phrId'+this.idPostfix+'" name="phrId" type="hidden" title="档案编号"/>'
				+ '<input id="empiId'+this.idPostfix+'" name="empiId" type="hidden" title="EMPIID"/>'
				+ '<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">'
				+ '<tr>'
				+ '<td width="18%" colspan="2" align="center"><font color="#FF0000"><span id="SFRQ'+this.idPostfix+'"><strong>随访日期</strong></span></font></td>'
				+ '<td colspan="3"><div id="div_visitDate'+this.idPostfix+'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ ' <td width="18%" colspan="2" align="center"><strong>危害度</strong></td>'
				+ '<td colspan="3" style="line-height:26px;">'
				+ '<input id="riskFactor_1'+this.idPostfix+'" type="radio" name="riskFactor" value="1"/>口头威胁，喊叫，但没有打砸行为  <br />' 
				+ '<input id="riskFactor_2'+this.idPostfix+'" type="radio" name="riskFactor" value="2"/>打砸行为，局限在家里，针对财物，能被劝说制止  <br />' 
				+ '<input id="riskFactor_3'+this.idPostfix+'" type="radio" name="riskFactor" value="3"/>明显打砸行为，不分场合，针对财物。不能接受劝说而停止  <br />' 
				+ '<input id="riskFactor_4'+this.idPostfix+'" type="radio" name="riskFactor" value="4"/>持续的打砸行为，不分场合，针对财物或人，不能接受劝说而停止  <br />'
				+ '<input id="riskFactor_5'+this.idPostfix+'" type="radio" name="riskFactor" value="5"/>持管制性危险武器的针对人的任何暴力行为，或者纵火，爆炸等行为' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<tr>'
				+ '<td width="18%" colspan="2" align="center"><strong>危险性</strong></td>'
				+ '<td colspan="3"> ' 
				+ '<input id="dangerousGrade_0'+this.idPostfix+'" type="radio" name="dangerousGrade" value="0"/>0级 '
				+ '<input id="dangerousGrade_1'+this.idPostfix+'" type="radio" name="dangerousGrade" value="1"/>1级'
				+ '<input id="dangerousGrade_2'+this.idPostfix+'" type="radio" name="dangerousGrade" value="2"/>2级'
				+ '<input id="dangerousGrade_3'+this.idPostfix+'" type="radio" name="dangerousGrade" value="3"/>3级'
				+ '<input id="dangerousGrade_4'+this.idPostfix+'" type="radio" name="dangerousGrade" value="4"/>4级'
				+ '<input id="dangerousGrade_5'+this.idPostfix+'" type="radio" name="dangerousGrade" value="5"/>5级'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>目前症状</strong></td>'
				+ '<td colspan="3" style="line-height:26px;">'
				+ '<input id="symptom_01'+this.idPostfix+'" type="checkbox" name="symptom" value="01"/>幻觉 '
				+ '<input id="symptom_02'+this.idPostfix+'" type="checkbox" name="symptom" value="02"/>交流困难'
				+ '<input id="symptom_03'+this.idPostfix+'" type="checkbox" name="symptom" value="03"/>猜疑'
				+ '<input id="symptom_04'+this.idPostfix+'" type="checkbox" name="symptom" value="04"/>喜怒无常'
				+ '<input id="symptom_05'+this.idPostfix+'" type="checkbox" name="symptom" value="05"/>行为怪异'
				+ '<input id="symptom_06'+this.idPostfix+'" type="checkbox" name="symptom" value="06"/>兴奋话多<br />'
				+ '<input id="symptom_07'+this.idPostfix+'" type="checkbox" name="symptom" value="07"/>伤人毁物'
				+ '<input id="symptom_08'+this.idPostfix+'" type="checkbox" name="symptom" value="08"/>悲观厌世'
				+ '<input id="symptom_09'+this.idPostfix+'" type="checkbox" name="symptom" value="09"/>无故外走'
				+ '<input id="symptom_10'+this.idPostfix+'" type="checkbox" name="symptom" value="10"/>自语自笑'
				+ '<input id="symptom_11'+this.idPostfix+'" type="checkbox" name="symptom" value="11"/>孤僻懒散'
				+ '<input id="symptom_99'+this.idPostfix+'" type="checkbox" name="symptom" value="99"/>其他'
				+ '<input id="symptomText'+this.idPostfix+'" type="text" name="symptomText" class="input_btline" />'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>自知力</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="insight_1'+this.idPostfix+'" type="radio" name="insight" value="1"/>自知力完全　　' 
				+ '<input id="insight_2'+this.idPostfix+'" type="radio" name="insight" value="2"/>自知力不全　　' 
				+ '<input id="insight_3'+this.idPostfix+'" type="radio" name="insight" value="3"/>自知力缺失' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>睡眠情况</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="sleepQuality_1'+this.idPostfix+'" type="radio" name="sleepQuality" value="1"/>良好   '
				+ '<input id="sleepQuality_2'+this.idPostfix+'" type="radio" name="sleepQuality" value="2"/>一般   ' 
				+ '<input id="sleepQuality_3'+this.idPostfix+'" type="radio" name="sleepQuality" value="3"/>较差'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>饮食情况</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="eatQuality_1'+this.idPostfix+'" type="radio" name="eatQuality" value="1"/>良好   '
				+ '<input id="eatQuality_2'+this.idPostfix+'" type="radio" name="eatQuality" value="2"/>一般   ' 
				+ '<input id="eatQuality_3'+this.idPostfix+'" type="radio" name="eatQuality" value="3"/>较差' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="5" align="center"><strong>社<br/>会<br/>功<br/>能<br/>情<br/>况</strong></td>'
				+ '<td><strong>个人生活料理</strong></td>'
				+ '<td colspan="3">'
				+ '<input id="liveQuality_1'+this.idPostfix+'" type="radio" name="liveQuality" value="1"/>良好   '
				+ '<input id="liveQuality_2'+this.idPostfix+'" type="radio" name="liveQuality" value="2"/>一般   ' 
				+ '<input id="liveQuality_3'+this.idPostfix+'" type="radio" name="liveQuality" value="3"/>较差'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>家务劳动</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="houseWork_1'+this.idPostfix+'" type="radio" name="houseWork" value="1"/>良好   ' 
				+ '<input id="houseWork_2'+this.idPostfix+'" type="radio" name="houseWork" value="2"/>一般   ' 
				+ '<input id="houseWork_3'+this.idPostfix+'" type="radio" name="houseWork" value="3"/>较差' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>生产劳动及工作</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="productiveLabor_1'+this.idPostfix+'" type="radio" name="productiveLabor" value="1"/>良好   ' 
				+ '<input id="productiveLabor_2'+this.idPostfix+'" type="radio" name="productiveLabor" value="2"/>一般   ' 
				+ '<input id="productiveLabor_3'+this.idPostfix+'" type="radio" name="productiveLabor" value="3"/>较差' 
				+ '<input id="productiveLabor_9'+this.idPostfix+'" type="radio" name="productiveLabor" value="9"/>此项不适用' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>学习能力</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="study_1'+this.idPostfix+'" type="radio" name="study" value="1"/>良好   ' 
				+ '<input id="study_2'+this.idPostfix+'" type="radio" name="study" value="2"/>一般   ' 
				+ '<input id="study_3'+this.idPostfix+'" type="radio" name="study" value="3"/>较差' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>社会人际交往</strong></td>'
				+ '<td colspan="6">'
				+ '<input id="social_1'+this.idPostfix+'" type="radio" name="social" value="1"/>良好   ' 
				+ '<input id="social_2'+this.idPostfix+'" type="radio" name="social" value="2"/>一般   ' 
				+ '<input id="social_3'+this.idPostfix+'" type="radio" name="social" value="3"/>较差' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>患病对家庭社会的影响</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="familySocialImpact_1'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="1"/>轻度滋事<input id="lightAffray'+this.idPostfix+'" type="text" name="lightAffray" class="width30 input_btline" />次   ' 
				+ '<input id="familySocialImpact_2'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="2"/>肇事<input id="causeTrouble'+this.idPostfix+'" type="text" name="causeTrouble" class="width30 input_btline" />次  ' 
				+ '<input id="familySocialImpact_3'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="3"/>肇祸<input id="causeAccident'+this.idPostfix+'" type="text" name="causeAccident" class="width30 input_btline" />次'
				+ '<input id="familySocialImpact_4'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="4"/>自伤<input id="selfHurt'+this.idPostfix+'" type="text" name="selfHurt" class="width30 input_btline" />次   ' 
				+ '<input id="familySocialImpact_5'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="5"/>自杀未遂<input id="suicide'+this.idPostfix+'" type="text" name="suicide" class="width30 input_btline" />次    ' 
				+ '<input id="familySocialImpact_0'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="0"/>无'
				+ '</td>   '
				+ ' </tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>关锁情况</strong></td>'
				+ ' <td colspan="3">' 
				+ '<input id="closeDoor_1'+this.idPostfix+'" type="radio" name="closeDoor" value="1"/>无关锁  ' 
				+ '<input id="closeDoor_2'+this.idPostfix+'" type="radio" name="closeDoor" value="2"/>关锁  ' 
				+ '<input id="closeDoor_3'+this.idPostfix+'" type="radio" name="closeDoor" value="3"/>关锁已解除' 
				+ '</td>'
				+ '</tr>'
				+ ' <tr>'
				+ '<td colspan="2" align="center"><strong>住院情况</strong></td>'
				+ '<td colspan="3" style="line-height:26px;"><table boder="0"  cellspacing="0" cellpadding="0" width="100%"><tr><td colspan="2">' 
				+ '<input id="hospitalization_0'+this.idPostfix+'" type="radio" name="hospitalization" value="0"/>从未住院 '
				+ '<input id="hospitalization_1'+this.idPostfix+'" type="radio" name="hospitalization" value="1"/>目前正在住院  '
				+ '<input id="hospitalization_2'+this.idPostfix+'" type="radio" name="hospitalization" value="2"/>既往住院，现未住院'
				+ '</td><tr>'
				+ '<td width="15%" align="right">末次出院时间：</td><td><div id="div_lastHospitalizationTime'+this.idPostfix+'"></div></td></tr></table>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>实验室检查</strong></td>'
				+ '<td colspan="3">'
				+ '<input id="isLabCheckup_1'+this.idPostfix+'" type="radio" name="isLabCheckup" value="1"/>无   '
				+ '<input id="isLabCheckup_2'+this.idPostfix+'" type="radio" name="isLabCheckup" value="2"/>有' 
				+'<input id="labCheckup'+this.idPostfix+'" type="text" name="labCheckup" title="实验室检查描述" class="width200 input_btline"/>'
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><font color="#FF0000"><span id="FYYCX'+this.idPostfix+'"><strong>服药依从性</strong></span></font></td>'
				+ '<td colspan="3"><div id="div_medicine'+this.idPostfix+'">'
				+ '<input id="medicine_1'+this.idPostfix+'" type="radio" name="medicine" value="1"/>规律  '
				+ '<input id="medicine_2'+this.idPostfix+'" type="radio" name="medicine" value="2"/>间断  '
				+ '<input id="medicine_3'+this.idPostfix+'" type="radio" name="medicine" value="3"/>不服药' 
				+ '</div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>药物不良反应</strong></td>'
				+ '<td colspan="3" >'
				+ '<input id="adverseReactions_n'+this.idPostfix+'" type="radio" name="adverseReactions" value="n"/>无   '
				+ '<input id="adverseReactions_y'+this.idPostfix+'" type="radio" name="adverseReactions" value="y"/>有   '
				+ '<input id="adverseReactionsText'+this.idPostfix+'" type="text" name="adverseReactionsText" title="不良反应描述" class="width200 input_btline"/>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>治疗效果</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="treatment_1'+this.idPostfix+'" type="radio" name="treatment" value="1"/>痊愈  ' 
				+ '<input id="treatment_2'+this.idPostfix+'" type="radio" name="treatment" value="2"/>好转  ' 
				+ '<input id="treatment_3'+this.idPostfix+'" type="radio" name="treatment" value="3"/>无变化  ' 
				+ '<input id="treatment_4'+this.idPostfix+'" type="radio" name="treatment" value="4"/>加重' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="3" align="center"><strong>是<br/>否<br/>转<br/>诊</strong></td>'
				+ '<td></td>'
				+ '<td colspan="3">'
				+ '<input id="referral_n'+this.idPostfix+'" type="radio" name="referral" value="n"/>否   ' 
				+ '<input id="referral_y'+this.idPostfix+'" type="radio" name="referral" value="y"/>是' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center"><strong>转诊原因</strong></td>'
				+ '<td colspan="3"><input id="reason'+this.idPostfix+'" type="text" name="reason" style="width:82%" class="input_btline"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center"><strong>转诊至机构及科室</strong></td>'
				+ '<td colspan="3"><input id="doccol'+this.idPostfix+'" type="text" name="doccol" style="width:82%" class="input_btline"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="6" align="center"><strong>用<br/>药<br/>情<br/>况</strong></td>'
				+ '<td align="center"><strong>药物1</strong><input id="recordId_1'+this.idPostfix+'" name="recordId_1" type="hidden" title="药物记录序号"/><input id="visitId_1'+this.idPostfix+'" name="visitId_1" type="hidden" title="随访记录序号"/></td>'
				+ '<td colspan="3"><div id="div_medicineName_1'+this.idPostfix+'" name="medicineName_1"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="12%" align="center"><span id="YFYX_1'+this.idPostfix+'"><strong>用法用量</strong></span></td>'
				+ '<td colspan="3"><table boder="0"  cellspacing="0" cellpadding="0" width="100%"><tr>'
				+ '<td width="25%"><input id="days_1'+this.idPostfix+'" name="days_1" value="1" type="hidden" title="天数"/><span id="MRY_1'+this.idPostfix+'">每日(月)<span><input id="medicineFrequency_1'+this.idPostfix+'" type="text" name="medicineFrequency_1" class="width80 input_btline" /><span id="CS_1'+this.idPostfix+'">次</span></td>'
				+ '<td width="25%"><span id="MCJL_1'+this.idPostfix+'">每次剂量</span><input id="medicineDosage_1'+this.idPostfix+'" type="text" name="medicineDosage_1" class="width105 input_btline" /></td>'
				+ '<td><input id="medicineUnit_1'+this.idPostfix+'" type="text" name="medicineUnit_1" class="width80"  style="border:none;" disabled/></td>'
				+ '</tr></table></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center"><strong>药物2</strong><input id="recordId_2'+this.idPostfix+'" name="recordId_2" type="hidden" title="药物记录序号"/><input id="visitId_2'+this.idPostfix+'" name="visitId_2" type="hidden" title="随访记录序号"/></td>'
				+ '<td colspan="3"><div id="div_medicineName_2'+this.idPostfix+'" name="medicineName_2"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center"><span id="YFYX_2'+this.idPostfix+'"><strong>用法用量</strong></span></td>'
				+ '<td colspan="3"><table boder="0"  cellspacing="0" cellpadding="0" width="100%"><tr>'
				+ '<td width="25%"><input id="days_2'+this.idPostfix+'" name="days_2" value="1" type="hidden" title="天数"/><span id="MRY_2'+this.idPostfix+'">每日(月)<span><input id="medicineFrequency_2'+this.idPostfix+'" type="text" name="medicineFrequency_2" class="width80 input_btline" /><span id="CS_2'+this.idPostfix+'">次</span></td>'
				+ '<td width="25%"><span id="MCJL_2'+this.idPostfix+'">每次剂量</span><input id="medicineDosage_2'+this.idPostfix+'" type="text" name="medicineDosage_2" class="width105 input_btline" /></td>'
				+ '<td><input id="medicineUnit_2'+this.idPostfix+'" type="text" name="medicineUnit_2" class="width80"  style="border:none;" disabled/></td>'
				+ '</tr></table></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center"><strong>药物3</strong><input id="recordId_3'+this.idPostfix+'" name="recordId_3" type="hidden" title="药物记录序号"/><input id="visitId_3'+this.idPostfix+'" name="visitId_3" type="hidden" title="随访记录序号"/></td>'
				+ '<td colspan="3"><div id="div_medicineName_3'+this.idPostfix+'" name="medicineName_3"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center"><span id="YFYX_3'+this.idPostfix+'"><strong>用法用量</strong></span></td>'
				+ '<td colspan="3"><table boder="0"  cellspacing="0" cellpadding="0" width="100%"><tr>'
				+ '<td width="25%"><input id="days_3'+this.idPostfix+'" name="days_3" value="1" type="hidden" title="天数"/><span id="MRY_3'+this.idPostfix+'">每日(月)</span><input id="medicineFrequency_3'+this.idPostfix+'" type="text" name="medicineFrequency_3" class="width80 input_btline" /><span id="CS_3'+this.idPostfix+'">次</span></td>'
				+ '<td width="25%"><span id="MCJL_3'+this.idPostfix+'">每次剂量</span><input id="medicineDosage_3'+this.idPostfix+'" type="text" name="medicineDosage_3" class="width105 input_btline" /></div></td>'
				+ '<td><input id="medicineUnit_3'+this.idPostfix+'" type="text" name="medicineUnit_3" class="width80"  style="border:none;" disabled/></td>'
				+ '</tr></table></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>康复措施</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="healing_1'+this.idPostfix+'" type="checkbox" name="healing" value="1"/>生活劳动能力 ' 
				+ '<input id="healing_2'+this.idPostfix+'" type="checkbox" name="healing" value="2"/>职业训练 ' 
				+ '<input id="healing_3'+this.idPostfix+'" type="checkbox" name="healing" value="3"/>学习能力 ' 
				+ '<input id="healing_4'+this.idPostfix+'" type="checkbox" name="healing" value="4"/>社会交往 ' 
				+ '<input id="healing_5'+this.idPostfix+'" type="checkbox" name="healing" value="5"/>其他' 
				+ '<input id="healingText'+this.idPostfix+'" type="text" name="healingText" class="input_btline" style="width:26%;"/>' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><font color="#FF0000"><span id="BCSFFL'+this.idPostfix+'"><strong>本次随访分类</strong></span></font></td>'
				+ '<td colspan="3"><div id="div_visitType'+this.idPostfix+'">' 
				+ '<input id="visitType_1'+this.idPostfix+'" type="radio" name="visitType" value="1"/>不稳定 ' 
				+ '<input id="visitType_2'+this.idPostfix+'" type="radio" name="visitType" value="2"/>基本稳定  ' 
				+ '<input id="visitType_3'+this.idPostfix+'" type="radio" name="visitType" value="3"/>稳定  ' 
				+ '<input id="visitType_0'+this.idPostfix+'" type="radio" name="visitType" value="0"/>未访到' 
				+ '</div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><font color="#FF0000"><strong>转归</strong></font></td>'
				+ '<td colspan="3"><table boder="0"  cellspacing="0" cellpadding="0" width="100%"><tr><td width="230"><div id="div_visitEffect'+this.idPostfix+'">' 
				+ '<input id="visitEffect_1'+this.idPostfix+'" type="radio" name="visitEffect" value="1"/>继续随访 ' 
				+ '<input id="visitEffect_2'+this.idPostfix+'" type="radio" name="visitEffect" value="2"/>暂时失访  ' 
				+ '<input id="visitEffect_9'+this.idPostfix+'" type="radio" name="visitEffect" value="9"/>终止管理  </div></td><td>' 
				+ '<input id="lostReason'+this.idPostfix+'" type="text" name="lostReason" title="原因" size="50" class="input_btline"/></td></tr></table>' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>下次随访日期</strong></td>'
				+ '<td ><div id="div_nextDate'+this.idPostfix+'"></div></td>'
				+ '<td width="15%" align="center"><font color="#FF0000"><span id="SFYSQM'+this.idPostfix+'"><strong>随访医生签名</strong></span></font></td>'
				+ '<td ><div id="div_visitDoctor'+this.idPostfix+'"></div><input id="visitUnit'+this.idPostfix+'" name="visitUnit" type="hidden" title="医生机构"/></td>'
				+ '</tr></table></div>';
		return html;
	}
}