$package("chis.application.psy.script.html");

chis.application.psy.script.html.PsychosisRecordHtmlTemplate = {
	getPsyRecordHTMLTemplate : function() {
		
		var html = '<div class="my">'
				+ '<input id="phrId'+this.idPostfix+'" name="phrId" type="hidden" title="档案编号"/>'
				+ '<input id="empiId'+this.idPostfix+'" name="empiId" type="hidden" title="EMPIID"/>'
				+ '<div style="display:none">'
				+ '<input id="status_0'+this.idPostfix+'" type="radio" name="status" value="0" checked="true" title="档案状态-正常" />'
				+ '<input id="status_1'+this.idPostfix+'" type="radio" name="status" value="1" title="档案状态-注销" />'
				+'</div>'
				+ '<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">'
				+ '<tr>'
				+ '<td colspan="2" width="22%" align="center"><font color="#FF0000"><strong>责任医生</strong></font></td>'
				+ ' <td width="28%"><div id="div_manaDoctorId'+this.idPostfix+'"></div></td>'
				+ '<td width="22%" align="center"><strong>管辖机构</strong></td>'
				+ '<td > <div id="div_manaUnitId'+this.idPostfix+'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ ' <td colspan="2" align="center"><strong>监护人姓名</strong></td>'
				+ ' <td > <input id="guardianName'+this.idPostfix+'" type="text" name="guardianName" class="width200 input_btline" /></td>'
				+ '<td align="center"><strong>与患者关系</strong></td>'
				+ '<td ><div id="div_guardianRelation'+this.idPostfix+'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>监护人住址</strong></td>'
				+ '<td > <div id="div_guardianAddress'+this.idPostfix+'"></div></td>'
				+ '<td align="center"><strong>监护人电话</strong></td>'
				+ '<td > <input id="guardianPhone'+this.idPostfix+'" type="text" name="guardianPhone" class="width200 input_btline" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>辖区村（居）委会联系人</strong></td>'
				+ '<td ><input id="VNCLinkMan'+this.idPostfix+'" type="text" name="VNCLinkMan" class="width200 input_btline" /></td>'
				+ '<td align="center"><strong>辖区村（居）委会联系电话</strong></td>'
				+ '<td><input id="VNCLinkPhone'+this.idPostfix+'" type="text" name="VNCLinkPhone" class="width200 input_btline" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="3" align="center"><strong>知情同意</strong></td>'
				+ '<td align="center"></td>'
				+ '<td colspan="3">' 
				+ '<input id="informedConsent_1'+this.idPostfix+'" type="radio" name="informedConsent" value="1"/>同意参加管理 '
				+ '<input id="informedConsent_0'+this.idPostfix+'" type="radio" name="informedConsent" value="0"/>不同意参加管理' 
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center">签字</td>'
				+ '<td colspan="3"><input id="icSign'+this.idPostfix+'" type="text" name="icSign" class="width200 input_btline" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center">签字时间</td>'
				+ '<td colspan="3"><div id="div_icDate'+this.idPostfix+'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>初次发病时间</strong></td>'
				+ '<td colspan="3"><div id="div_diseasedTime'+this.idPostfix+'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>既往主要症状</strong></td>'
				+ '<td colspan="3" style="line-height:24px;">' 
				+ '<input id="pastSymptom_01'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="01"/>幻觉  '
				+ '<input id="pastSymptom_02'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="02"/>交流困难' 
				+ '<input id="pastSymptom_03'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="03"/>猜疑 '
				+ '<input id="pastSymptom_04'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="04"/>喜怒无常'
				+ '<input id="pastSymptom_05'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="05"/>行为怪异'
				+ '<input id="pastSymptom_06'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="06"/>兴奋话多<br />'
				+ '<input id="pastSymptom_07'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="07"/>伤人毁物'
				+ '<input id="pastSymptom_08'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="08"/>悲观厌世'
				+ '<input id="pastSymptom_09'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="09"/>无故外走'
				+ '<input id="pastSymptom_10'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="10"/>自语自笑'
				+ '<input id="pastSymptom_11'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="11"/>孤僻懒散'
				+ '<input id="pastSymptom_99'+this.idPostfix+'" type="checkbox" name="pastSymptom" value="99"/>其他'
				+ '<input id="pastSymptomText'+this.idPostfix+'" type="text" name="pastSymptomText" class="input_btline" />' 
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="2" align="center"><strong>既往治疗情况</strong></td>'
				+ '<td align="center" width="10%">门诊</td>'
				+ '<td colspan="3" style="line-height:26px;"><table boder="0"  cellspacing="0" cellpadding="0" width="100%"><tr><td colspan="2">'
				+ '<input id="pastClinic_1'+this.idPostfix+'" type="radio" name="pastClinic" value="1"/>未治'
				+ '<input id="pastClinic_2'+this.idPostfix+'" type="radio" name="pastClinic" value="2"/>间断门诊治疗'
				+ '<input id="pastClinic_3'+this.idPostfix+'" type="radio" name="pastClinic" value="3"/>连续门诊治疗'
				+ '</td></tr>'
				+ '<tr><td width="24%" align="right">首次抗精神病药治疗时间</td>'
				+ '<td><div id="div_firstCureTime'+this.idPostfix+'"></div></td></tr></table>'
				+'</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td align="center">住院</td>'
				+ '<td colspan="3">曾住精神专科医院/综合医院精神专科<input id="pastHospitalizationText'+this.idPostfix+'" type="text" name="pastHospitalizationText" class="width30 input_btline" />次</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>目前诊断情况</strong></td>'
				+ '<td colspan="3"><table boder="0"  cellspacing="0" cellpadding="0" width="100%"><tr>'
				+ '<td width="30%">诊断<input id="recentDiagnosis'+this.idPostfix+'" type="text" name="recentDiagnosis" class="width145 input_btline" /></td>' 
				+ '<td width="40%">确诊医院<input id="recentDiagnoseHospital'+this.idPostfix+'" type="text" name="recentDiagnoseHospital" class="width185 input_btline" /></td>' 
				+ '<td width="10%" align="right">确诊日期</td><td><div id="div_recentDiagnoseTime'+this.idPostfix+'"></div></td></tr></table>'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>最近一次治疗效果</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="recentTreatResult_1'+this.idPostfix+'" type="radio" name="recentTreatResult" value="1"/>痊愈' 
				+ '<input id="recentTreatResult_2'+this.idPostfix+'" type="radio" name="recentTreatResult" value="2"/>好转' 
				+ '<input id="recentTreatResult_3'+this.idPostfix+'" type="radio" name="recentTreatResult" value="3"/>无变化'
				+ '<input id="recentTreatResult_4'+this.idPostfix+'" type="radio" name="recentTreatResult" value="4"/>加重'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>患病对家庭社会的影响</strong></td>'
				+ '<td colspan="3" style="line-height:26px;">' 
				+ '<input id="familySocialImpact_1'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="1" />轻度滋事<input id="lightAffray'+this.idPostfix+'" type="text" name="lightAffray" class="width30 input_btline" />次&nbsp;&nbsp;   ' 
				+ '<input id="familySocialImpact_2'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="2" />肇事<input id="causeTrouble'+this.idPostfix+'" type="text" name="causeTrouble" class="width30 input_btline" />次&nbsp;&nbsp;   ' 
				+ '<input id="familySocialImpact_3'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="3" />肇祸<input id="causeAccident'+this.idPostfix+'" type="text" name="causeAccident" class="width30 input_btline" />次<br />'
				+ '<input id="familySocialImpact_4'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="4" />自伤<input id="selfHurt'+this.idPostfix+'" type="text" name="selfHurt" class="width30 input_btline" />次&nbsp;&nbsp;  ' 
				+ '<input id="familySocialImpact_5'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="5"/>自杀未遂<input id="suicide'+this.idPostfix+'" type="text" name="suicide" class="width30 input_btline" />次&nbsp;&nbsp;  ' 
				+ '<input id="familySocialImpact_0'+this.idPostfix+'" type="checkbox" name="familySocialImpact" value="0"/>无'
				+ '</td>  '
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>关锁情况</strong></td>'
				+ '<td colspan="3">' 
				+ '<input id="closeDoor_1'+this.idPostfix+'" type="radio" name="closeDoor" value="1"/>无关锁'
				+ '<input id="closeDoor_2'+this.idPostfix+'" type="radio" name="closeDoor" value="2"/>关锁'
				+ '<input id="closeDoor_3'+this.idPostfix+'" type="radio" name="closeDoor" value="3"/>关锁已解除'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>经济状况</strong></td>'
				+ '<td colspan="3">'
				+ '<input id="economicConditions_1'+this.idPostfix+'" type="radio" name="economicConditions" value="1"/>贫困，在当地贫困线标准以下  '
				+ '<input id="economicConditions_2'+this.idPostfix+'" type="radio" name="economicConditions" value="2"/>非贫困 '
				+ '<input id="economicConditions_3'+this.idPostfix+'" type="radio" name="economicConditions" value="3"/>不详'
				+ '</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>专科医生的意见(如果有请记录)</strong></td>'
				+ '<td colspan="3"><input id="specialistOpinion'+this.idPostfix+'" type="text" name="specialistOpinion" style="width:88%;" class="input_btline"/></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" align="center"><strong>填表日期</strong></td>'
				+ '<td ><div id="div_fillTableDate'+this.idPostfix+'"></div></td>'
				+ '<td align="center"><strong>医生签字</strong></td>'
				+ '<td >' 
				+ '<div id="div_doctorSign'+this.idPostfix+'"></div>' 
				+ '<input id="doctorUnit'+this.idPostfix+'" name="doctorUnit" type="hidden" title="医生机构"/>'
				+ '</td>'
				+ '</tr>' + '</table>' + '</div>';

		return html;
	}
}