$package("chis.application.tb.script");

chis.application.tb.script.TuberculosisVisitHtmlTemplate = {
	getTBVisitHTMLTemplate : function() {
		var html = '<div class="my">'
				+ '<input id="visitId'+this.idPostfix+'" name="visitId" type="hidden" title="随访ID"/>'
				+ '<input id="phrId'+this.idPostfix+'" name="phrId" type="hidden" title="档案编号"/>'
				+ '<input id="empiId'+this.idPostfix+'" name="empiId" type="hidden" title="EMPIID"/>'
				+ '<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">'
				+ '<tr>'
				
				+ '<td colspan="2"><label for="visitDate' + this.idPostfix +'"><div align="center"><strong>随访时间</strong></div></label></td>'
				+ '<td><div id="div_visitDate' + this.idPostfix +'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="2"><div align="center"><strong>治疗月序</strong></div></td>'
				+ '<td valign="center">第'
				+ '<input name="treatmentMonthOrder" type="text" id="treatmentMonthOrder' + this.idPostfix +'" />'
				+ '月</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="2"><div align="center"><strong>督导人员选择</strong></div></td>'
				+ '<td valign="top"><label for="supervisor_1' + this.idPostfix +'"><input type="radio" name="supervisor" id="supervisor_1' + this.idPostfix +'" value="1" />'
				+ '医生 </label>'
				+ '<label for="supervisor_2' + this.idPostfix +'"><input type="radio" name="supervisor" id="supervisor_2' + this.idPostfix +'" value="2" />'
				+ '家属 </label>'
				+ '<label for="supervisor_3' + this.idPostfix +'"><input type="radio" name="supervisor" id="supervisor_3' + this.idPostfix +'" value="3" />'
				+ '自服药 </label>'
				+ '<label for="supervisor_4' + this.idPostfix +'"><input type="radio" name="supervisor" id="supervisor_4' + this.idPostfix +'" value="4" />'
				+ '其他 </label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="2"><div align="center"><strong>随访方式</strong></div></td>'
				+ '<td width="425" valign="center"><label for="visitType_1' + this.idPostfix +'">'
				+ '<input name="visitType" type="radio" id="visitType_1' + this.idPostfix +'" value="1" />'
				+ '门诊 </label>'
				+ '<label for="visitType_2' + this.idPostfix +'"><input name="visitType" type="radio" id="visitType_2' + this.idPostfix +'" value="2" />'
				+ '家庭 </label>'
				+ '<label for="visitType_3' + this.idPostfix +'"><input name="visitType" type="radio" id="visitType_3' + this.idPostfix +'" value="3" />'
				+ '电话 </label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="medium" colspan="2" rowspan="2"><div align="center"><strong>症状及体征</strong></div></td>'
				+ '<td valign="top"><label for="symptomSign_0' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_0' + this.idPostfix +'" value="0" />'
				+ '没有症状 </label>'
				+ '<label for="symptomSign_1' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_1' + this.idPostfix +'" value="1" />'
				+ '咳嗽咳痰 </label>'
				+ '<label for="symptomSign_2' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_2' + this.idPostfix +'" value="2" />'
				+ '低热盗汗 </label>'
				+ '<label for="symptomSign_3' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_3' + this.idPostfix +'" value="3" />'
				+ '咯血或血痰 </label>'
				+ '<label for="symptomSign_4' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_4' + this.idPostfix +'" value="4" />'
				+ '胸痛消瘦 </label>'
				+ '<label for="symptomSign_5' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_5' + this.idPostfix +'" value="5" />'
				+ '恶心纳差 </lable><br/>'
				+ '<label for="symptomSign_6' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_6' + this.idPostfix +'" value="6" />'
				+ '关节疼痛 </label>'
				+ '<label for="symptomSign_7' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_7' + this.idPostfix +'" value="7" />'
				+ '头痛失眠 </label>'
				+ '<label for="symptomSign_8' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_8' + this.idPostfix +'" value="8" />'
				+ '视物模糊 </label>'
				+ '<label for="symptomSign_9' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_9' + this.idPostfix +'" value="9" />'
				+ '皮肤瘙痒、皮疹 </label>'
				+ '<label for="symptomSign_10' + this.idPostfix +'">'
				+ '<input name="symptomSign" type="checkbox" id="symptomSign_10' + this.idPostfix +'" value="10" />'
				+ '耳鸣、听力下降 </label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top">其他：'
				+ '<input name="otherSymptomSign" type="text" id="otherSymptomSign' + this.idPostfix +'" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="173" rowspan="2" valign="center"><div align="center"><strong>生活方式指导</strong></div></td>'
				+ '<td valign="top"><div align="center"><strong>吸烟</strong></div></td>'
				+ '<td valign="top"><input name="smokePerDay2" type="text" id="smokePerDay2' + this.idPostfix +'" size="3" />'
				+ '/'
				+ '<input name="smokeDay2" type="text" id="smokeDay2' + this.idPostfix +'" size="3" />'
				+ '支/天</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top"><div align="center"><strong>饮酒</strong></div></td>'
				+ '<td valign="top"><input name="drinkPerDay2" type="text" id="drinkPerDay2' + this.idPostfix +'" size="3" />'
				+ '/'
				+ '<input name="drinkDay2" type="text" id="drinkDay2' + this.idPostfix +'" size="3" />'
				+ '两/天</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="medium" rowspan="4"><div align="center"><strong>用<br/><br/>药</strong></div></td>'
				+ '<td width="186" valign="center"><div align="center"><strong>化疗方案</strong></div></td>'
				+ '<td valign="top"><input name="chemotherapy" type="text" id="chemotherapy' + this.idPostfix +'" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td width="186" valign="center"><div align="center"><strong>用法</strong></div></td>'
				+ '<td valign="top">'
				+ '<label for="medicineUsage_1' + this.idPostfix +'"><input type="radio" name="medicineUsage" id="medicineUsage_1' + this.idPostfix +'" value="1" />'
				+ '每日 </label>'
				+ '<label for="medicineUsage_2' + this.idPostfix +'"><input type="radio" name="medicineUsage" id="medicineUsage_2' + this.idPostfix +'" value="2" />'
				+ '间歇 </label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="center"><div align="center"><strong>药品剂型</strong></div></td>'
				+ '<td valign="top"><label for="medicineType_1' + this.idPostfix +'">'
				+ '<input name="medicineType" type="radio" id="medicineType_1' + this.idPostfix +'" value="1" />'
				+ '固定剂量复制剂</label>'
				+ '<label for="medicineType_2' + this.idPostfix +'">'
				+ '<input name="medicineType" type="radio" id="medicineType_2' + this.idPostfix +'" value="2" />'
				+ '散装药</label>'
				+ '<label for="medicineType_3' + this.idPostfix +'">'
				+ '<input name="medicineType" type="radio" id="medicineType_3' + this.idPostfix +'" value="3" />'
				+ '板式组合药</label>'
				+ '<label for="medicineType_4' + this.idPostfix +'">'
				+ '<input name="medicineType" type="radio" id="medicineType_4' + this.idPostfix +'" value="4" />'
				+ '注射剂</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="center"><div align="center"><strong>漏服药次数</strong></div></td>'
				+ '<td valign="top"><input type="text" name="missMedicineNum" id="missMedicineNum' + this.idPostfix +'" />次</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" valign="center"><div align="center"><strong>药物不良反应</strong></div></td>'
				+ '<td valign="top"><label for="medicineBadReaction_1' + this.idPostfix +'"><input' +
						' type="radio" name="medicineBadReaction" id="medicineBadReaction_1' + this.idPostfix +'" value="1" />'
				+ '无 </label>'
				+ '<label for="medicineBadReaction_2' + this.idPostfix +'"><input' +
						' type="radio" name="medicineBadReaction" id="medicineBadReaction_2' + this.idPostfix +'" value="2" />'
				+ '有 </label>'
				+ '<input type="text" name="medicineBadReactionDesc" id="medicineBadReactionDesc' + this.idPostfix +'" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" valign="center"><div align="center"><strong>并发症及合并症</strong></div></td>'
				+ '<td valign="top"><label for="complicationComorbidity_1' + this.idPostfix +'"><input ' +
						'type="radio" name="complicationComorbidity" id="complicationComorbidity_1' + this.idPostfix +'" value="1" />'
				+ '无 </label>'
				+ '<label for="complicationComorbidity_2' + this.idPostfix +'"><input ' +
						'type="radio" name="complicationComorbidity" id="complicationComorbidity_2' + this.idPostfix +'" value="2" />'
				+ '有 </label>'
				+ '<input type="text" name="complicationComorbidityDesc" id="complicationComorbidityDesc' + this.idPostfix +'" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="3" valign="center"><div align="center"><strong>转<br/>诊</strong></div></td>'
				+ '<td valign="center"><div align="center"><strong>科别</strong></div></td>'
				+ '<td valign="top"><input type="text" name="referralDivision" id="referralDivision' + this.idPostfix +'" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="center"><div align="center"><strong>原因</strong></div></td>'
				+ '<td valign="top"><input type="text" name="referralReason" id="referralReason' + this.idPostfix +'" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="center"><div align="center"><strong>2周内随访,随访结果</strong></div></td>'
				+ '<td valign="top"><input type="text" name="twoWeekReferralResult" id="twoWeekReferralResult' + this.idPostfix +'" /></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="2"><div align="center"><strong>处理意见</strong></div></td>'
				+ '<td valign="top"><div id="nextDate2' + this.idPostfix +'">'
				+ '<input type="text" name="processAdvice" id="processAdvice' + this.idPostfix +'" />'
				+ '</div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="2"><div align="center"><strong>下次随访时间</strong></div></td>'
				+ '<td valign="top"><div id="div_nextDate' + this.idPostfix +'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top" colspan="2"><div align="center"><strong>随访医生签名</strong></div></td>'
				+ '<td valign="top"><div id="div_visitDoctor' + this.idPostfix +'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td rowspan="2"><div align="center"><strong>停止治疗及原因</strong></div></td>'
				+ '<td><strong>出现停止治疗时间</strong></td>'
				+ '<td valign="top"><div id="div_stopTreatmentTime' + this.idPostfix +'"></div></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td><strong>停止治疗原因</strong></td>'
				+ '<td valign="top"><label for="stopTreatmentReason_1' + this.idPostfix +'"><input ' +
						'type="radio" name="stopTreatmentReason" id="stopTreatmentReason_1' + this.idPostfix +'" value="1" />'
				+ '完成疗程 </label>'
				+ '<label for="stopTreatmentReason_2' + this.idPostfix +'"><input' +
						' type="radio" name="stopTreatmentReason" id="stopTreatmentReason_2' + this.idPostfix +'" value="2" />'
				+ '死亡 </label>'
				+ '<label for="stopTreatmentReason_3' + this.idPostfix +'"><input' +
						' type="radio" name="stopTreatmentReason" id="stopTreatmentReason_3' + this.idPostfix +'" value="3" />'
				+ '丢失 </label>'
				+ '<label for="stopTreatmentReason_4' + this.idPostfix +'"><input' +
						' type="radio" name="stopTreatmentReason" id="stopTreatmentReason_4' + this.idPostfix +'" value="4" />'
				+ '转入耐多药治疗</label></td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td colspan="2" rowspan="2"><div align="center"><strong>全程管理情况</strong></div></td>'
				+ '<td valign="top">应访视患者'
				+ '<input name="shouldVisitNum" type="text" id="shouldVisitNum' + this.idPostfix +'" />'
				+ '次,<br/>实际访视'
				+ '<input type="text" name="actualVisitNum" id="actualVisitNum' + this.idPostfix +'" />'
				+ '次<br />'
				+ '患者在疗程中,应服药'
				+ '<input type="text" name="shouldMedicineNum" id="shouldMedicineNum' + this.idPostfix +'" />'
				+ '次,<br/>实际服药'
				+ '<input type="text" name="actualMedicineNum" id="actualMedicineNum' + this.idPostfix +'" />'
				+ '次,<br/>服药率<input id="medicineRate' + this.idPostfix +'">%</td>'
				+ '</tr>'
				+ '<tr>'
				+ '<td valign="top"><div id="div_assessDoctor' + this.idPostfix + '">评估医生签名</div></td>'

				+ '</tr></table></div>';
		return html;
	}
}