package com.chcit.spd.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SPDService service = new SPDService();
 * SPDServicePortType portType = service.getSPDServiceHttpSoap11Endpoint();
 * portType.putPOOrder(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SPDService", targetNamespace = "http://service.ws.spd.chcit.com", wsdlLocation = "http://10.2.202.138:27004/spd/services/SPDService?wsdl")
public class SPDService extends Service {

	private final static URL SPDSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.chcit.spd.ws.service.SPDService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.chcit.spd.ws.service.SPDService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.2.202.138:27004/spd/services/SPDService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.2.202.138:27004/spd/services/SPDService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SPDSERVICE_WSDL_LOCATION = url;
	}

	public SPDService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SPDService() {
		super(SPDSERVICE_WSDL_LOCATION, new QName(
				"http://service.ws.spd.chcit.com", "SPDService"));
	}

	/**
	 * 
	 * @return returns SPDServicePortType
	 */
	@WebEndpoint(name = "SPDServiceHttpSoap11Endpoint")
	public SPDServicePortType getSPDServiceHttpSoap11Endpoint() {
		return super.getPort(new QName("http://service.ws.spd.chcit.com",
				"SPDServiceHttpSoap11Endpoint"), SPDServicePortType.class);
	}

	/**
	 * 
	 * @return returns SPDServicePortType
	 */
	@WebEndpoint(name = "SPDServiceHttpSoap12Endpoint")
	public SPDServicePortType getSPDServiceHttpSoap12Endpoint() {
		return super.getPort(new QName("http://service.ws.spd.chcit.com",
				"SPDServiceHttpSoap12Endpoint"), SPDServicePortType.class);
	}

	/**
	 * 
	 * @return returns SPDServicePortType
	 */
	@WebEndpoint(name = "SPDServiceHttpEndpoint")
	public SPDServicePortType getSPDServiceHttpEndpoint() {
		return super.getPort(new QName("http://service.ws.spd.chcit.com",
				"SPDServiceHttpEndpoint"), SPDServicePortType.class);
	}

}
